### ISSUE TITLE
Add support in CycleStreets driver for reporterrors=1

### ISSUE THREAD

**Issue by mvl22** [ropensci/stplanr#105]
The CycleStreets V1 API had a new option `reporterrors` = `1` added to it a few months ago:

https://www.cyclestreets.net/api/v1/journey/

I recommend adding support for this, to catch reportable problems, e.g. unroutable OSM data.

Forthcoming V2 does this automatically (this option is essentially a backport, but avoids existing client implementations getting unexpected data).

**Comment by richardellison** [comment]
Thank you for the suggestion, I have added initial support for the option to the cyclestreets function.

**Comment by Robinlovelace** [comment]
Awesome work - now we just need CycleStreets.net to cover all of Australia and @richardellison will be able to use this for his work!

**Comment by mvl22** [comment]
Give us a GeoJSON of an area required and we can add to a future import.

**Comment by Robinlovelace** [comment]
Suggest we close this - think its working although I don't have a use case - if you could provide one @mvl22 I can test it.

**Comment by mvl22** [comment]
If you want to test it, try planning in e.g. Spain (which is not loaded on the PCT server):

/api/journey.json?key=yourapikey&itinerarypoints=2.7,41.3|2.71,41.2&plan=quietest&reporterrors=1

(obviously use your real key), and you'll see the error.

**Comment by Robinlovelace** [comment]
Tested as follows:

```r
route_cyclestreet(from = c(2.7, 41.3), to = c(2.71,41.2), reporterrors = T)
## Error in route_cyclestreet(from = c(2.7, 41.3), to = c(2.71, 41.2), reporterrors = T,  : 
##  Error: Waypoint #1 is too far from known cycle network.
```

Seems to report the error correctly so closing.
