### ISSUE TITLE
error in overline fxn

### ISSUE THREAD

**Issue by sckott** [ropensci/stplanr#111]
When trying the example from the vignette I get

``` r
library(stplanr); library(sp); library(leaflet)
data("flow", package = "stplanr")
data("cents", package = "stplanr")
l <- od2line(flow = flow, zones = cents)
l <- l[!l$Area.of.residence == l$Area.of.workplace,]
lgb <- spTransform(l, CRSobj = CRS("+init=epsg:27700"))
l$d_euclidean <- rgeos::gLength(lgb, byid = T)
l$d_fastroute <- routes_fast@data$length
routes_fast$All <- l$All
overline(routes_fast, "All", fun = sum)
#> Assertion failed: (!"should never be reached"), function itemsTree, file ../../../../src/geos-3.4.2/src/index/strtree/AbstractSTRtree.cpp, line 371.
```

same session info as #110 - and same error whether using CRAN version or current version on master here

**Comment by richardellison** [comment]
I can't reproduce the problem and have nearly exactly the same session info as you except I'm running Linux and not OSX and I'm using a newer version of the geos library. 

The error indicates it has something to do with the geos library. I'm running the same version of the rgeos package so it probably isn't that. I will have to try on a Mac and see if I can reproduce it.

Can you show me what the routes_fast SpatialLinesDataFrame summary looks like?

**Comment by sckott** [comment]
```r
<r> routes_fast
#> class       : SpatialLinesDataFrame
#> features    : 42
#> extent      : -1.550964, -1.510925, 53.80248, 53.83041  (xmin, xmax, ymin, ymax)
#> coord. ref. : NA
#> variables   : 7
#> names       :    plan,             start,            finish, length, time, waypoint, All
#> min values  : fastest, Back Ruthven View, Back Ruthven View,    895,  132,       22,   5
#> max values  : fastest,       Town Street,       Town Street,   4248, 1279,      127, 165
```

**Comment by richardellison** [comment]
Strangely when I run the same example I end up with:

```{r}
> routes_fast
class       : SpatialLinesDataFrame 
features    : 42 
extent      : -1.550964, -1.510925, 53.80248, 53.83041  (xmin, xmax, ymin, ymax)
coord. ref. : NA 
variables   : 7
names       :    plan,             start,            finish, length, time, waypoint, All 
min values  : fastest, Back Ruthven View, Back Ruthven View,   1318, 1097,      104,  10 
max values  : fastest,       Town Street,       Town Street,    975,  997,       99,  94
```

That being the case though, it really shouldn't make a difference as I would expect it to work with any valid SpatialLinesDataFrame (that yours appears to be). I'll have to do a bit more digging.

**Comment by Robinlovelace** [comment]
@sckott is this still not working? Will open again if so, but overall the function works although seems to be slow and produce unexpected results sometimes - think that's a separate issue though.

**Comment by sckott** [comment]
i'll have a look ⏲

**Comment by sckott** [comment]
@Robinlovelace with the example in https://github.com/ropensci/stplanr/issues/111#issue-174561946 I get 

```r
class       : SpatialLinesDataFrame 
features    : 85 
extent      : -1.550964, -1.510925, 53.80248, 53.83041  (xmin, xmax, ymin, ymax)
coord. ref. : NA 
variables   : 1
names       : All 
min values  :   5 
max values  : 825 
```

**Comment by Robinlovelace** [comment]
OK great, that seems like a reasonable output to me, at least before we switch to **sf**!

**Comment by sckott** [comment]
ok, good
