### ISSUE TITLE
Give meaningful error message when can't connect to routing service

### ISSUE THREAD

**Issue by mem48** [ropensci/stplanr#114]
If line2route can't connect to cycle streets it returns lots of meaningless errors it would be helpful to return a warning "unable to connect to cycle streets" to save lots of debugging pain

**Comment by richardellison** [comment]
The function now returns an error if it is unable to connect (or it connects but receives an empty result).

**Comment by Robinlovelace** [comment]
Closing as @richardellison has fixed it. Please give it a try if you get a chance @mem48 - you can get the latest version with `devtools::install_github("ropensci/stplanr")`.
