### ISSUE TITLE
httr usage

### ISSUE THREAD

**Issue by sckott** [ropensci/stplanr#115]
Just a few thoughts on best practice for using httr, applies to 3 fxns in the pkg AFAICT 

* the URL for each request is constructed manually. You could make this easier by e.g. in the `route_graphhopper` fxn 

```r
args <- list(
  point = paste0(from[2:1], collapse = ","),
  point = paste0(to[2:1], collapse = ","),
  vehicle = vehicle,
  locale = "en-US",
  debug = 'true', 
  points_encoded = 'false',
  key = pat
)

res <- httr::GET(paste0(base_url, "route"), query = args, httr::verbose())
```

`httr` does URL encoding for you, so you don't have to do it yourself

* In this line `txt <- httr::content(httr::GET(request), as = "text")` I'd recommend splitting that up into the http request, and parsing separately. And in between checking that the request worked correctly. so eg.., 

```r
res <- httr::GET(request)
stop_for_status(res) # or warn_for_status(res)
txt <- httr::content(res, as = "text", encoding = "UTF-8") 
obj <- jsonlite::fromJSON(txt)
```

I often check that the `content-type` is correct as well (e.g., `stopifnot(temp$headers$content-type == 'application/json')`), b/c if that's not what you expect, then something is wrong. `stop_for_status()` is useful but you can do a custom function that checks the HTTP status code, then does parsing of the result, b/c e.g., `stop_for_status()` won't parse out error messages from the response body. And I threw in `encoding = "UTF-8"` in the `httr::content` call, should explicitly state encoding in that fxn now

**Comment by richardellison** [comment]
Good advice. I have made your suggested changes to the functions that currently use the httr package. 

This is probably also a good opportunity to standardise the use of the httr package for retrieving remote data. Some other functions in the package currently use the RCurl package directly.

**Comment by Robinlovelace** [comment]
Thanks Scott for the advice - this was my bad as I didn't know about correct **httr** usage when I set that up. I think we should remove use of the **RCurl** package - you up for taking a look that Richard, maybe as part of https://github.com/ropensci/stplanr/pull/102 ? I think some its used in code you wrote.

Just to clarify, after https://github.com/ropensci/stplanr/commit/082eca997b344505f9321ef3de080f83b10f469d what else do we need to do to close this?

Really appreciate that code example btw - will use that style in future functions that call APIs - was wondering what best practice was and now I know which is really, really useful.

**Comment by sckott** [comment]
no bad at all, and dont consider my suggestions the "correct way", but rather what I've found to be the best usage pattern thus far

I'll have a look at the PR

**Comment by richardellison** [comment]
I'll go through the rest of the functions and replace any RCurl functions with httr. From habit I tend to use RCurl directly but certainly using httr is probably better practice (and that way we're consistent).

**Comment by Robinlovelace** [comment]
@sckott I've set `pat = NULL` as the default here: https://github.com/ropensci/stplanr/pull/119/commits/05018d4c2f7d9ca34f5f59f966db93b3d0619353

Any other suggestions welcome.

**Comment by sckott** [comment]
nothing else I can see at this point, nice work !
