### ISSUE TITLE
Line2Route does not return ID

### ISSUE THREAD

**Issue by mem48** [ropensci/stplanr#128]
Line2route used to return an ID column with which could be used to match the results to the original data it no longer returns this column. As the Start and Finish columns just contain 1 ,1, 1, there is no way to match the results to the original data.

**Comment by richardellison** [comment]
You can create your own ID column by using the row.names() function on the data slot of the SpatialLinesDataFrame. I have updated the function in #129 so it will add the ID column again.

**Comment by Robinlovelace** [comment]
I think this fixed it: https://github.com/ropensci/stplanr/pull/129

Thanks Richard.
