### ISSUE TITLE
Add functions for getting route network characteristics from OSM

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#130]
Could involve downloading OSM data with [**osmdata**](https://github.com/osmdatar/osmdata) by @mpadge. The thinking is to have a route (`r`) and then get statistics about conditions on the route by querying buffered data around it. This is probably best created as a series of modular self standing functions in the first instance, e.g.

`get_osmavspeed(r)` would report the average speed along the route. This would call another function, e.g.

``` r
get_osmspeeds <- function(r)
  if(is(object = routes_fast, "Spatial")) { # but not actually OSM data - will need another if to test that
    # get average speeds of roads along the route, either by sampling or summarising speeds of highways that correspond to the spatial object
  }
}
```

**Comment by mpadge** [comment]
If you've already got the route, three out of four (`get_osmavspeed`, `get_fastprox`, and `get_busstops`) would be trivial. `get_greenspace` would be easy in principle, but would require some fiddly decisions regarding how to define and measure green and non-green. Steps:

1. Let me know if you're envisioning these being used on pre-existing routes; and
2. If so, I reckon we could incorporate the 3/4 fairly easily.

**Comment by Robinlovelace** [comment]
Thanks for the fast response. It depends if the 'route' is from OSM directly or another source (e.g. national cartographic agency, which may not have that field) - I think the only tricky part is downloading OSM data in the precise buffer surrounding the route - that could have quite a complex structure, e.g.

```r
data("routes_fast")
b = buff_geo(routes_fast, width = 100)
plot(b)
```
![screenshot from 2016-10-19 15-05-35](https://cloud.githubusercontent.com/assets/1825120/19521983/876eefc0-960d-11e6-960f-91f2b08698d4.png)

**Comment by Robinlovelace** [comment]
In that case you may as well download the bounding box, but what about cases where you have a long, windy route?

**Comment by Robinlovelace** [comment]
Closing for now as this has gone stale. Many approaches including geofabric, osmdata (for small road networks) and Googles road speeds API: https://developers.google.com/maps/documentation/roads/speed-limits
