### ISSUE TITLE
Create line_merge function

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#135]
Idea: allow users to return lines from one `SpatialLines` object (`l2`) which match roughly the origins and destinations of those in another (the 'left' one, `l1`). I envision the following function, which returns another `SpatialLines` object:

```r
line_merge <-  function(l1, l2, distance, match) {
  ...
}
```

where distance is the distance in m, match is whether to match multiple lines and `crs_select_aeq()` can be used to select a projected CRS with units of 1m anywhere in the world.

And a method sketched below that could go into the function:

1: Transform the lines into a projected CRS.

2: Create 4 new columns for l and rds, which is the coordinates-origin and coordinates-destination

This can be done with line2od, e.g:

```
line2df(routes_fast[5:6,]) # beginning and end of routes
# A tibble: 2 x 5
  object        fx       fy        tx       ty
   <dbl>     <dbl>    <dbl>     <dbl>    <dbl>
1      1 -1.516749 53.82868 -1.511701 53.81167
2      2 -1.516749 53.82868 -1.524028 53.80399
```

3: Round the values of each column to the nearest n metres 

4: Create the new id as id = paste(fx, fy, tx, ty)

**Comment by Robinlovelace** [comment]
Update: the following code is moving towards a solution:



```r
# Aim: prototype geographical joining function

library(stplanr)

# Create data in projected CRS with units of m
rf = routes_fast[5:1,] # wrong order
l = flowlines[1:5,]
proj4string(rf) = CRS("+init=epsg:4326")
rf = spTransform(rf, CRS("+init=epsg:27700"))
l = spTransform(l, CRS("+init=epsg:27700"))

# Test mismatch
plot(l); plot(l[2,], lwd = 5, add = T)
plot(rf[2,], add = T) # does not match
```

![plot of chunk unnamed-chunk-1](figure/unnamed-chunk-1-1.png)

```r
# Merge based on ods
l_od_coords = line2df(l)
rf_od_coords = line2df(rf) 
sid1 = as.matrix(l_od_coords[-1])
sid2 = as.matrix(rf_od_coords[-1])

# install.packages("Hmisc")
m = Hmisc::find.matches(sid1, sid2, maxmatch = nrow(sid1),
                    tol = c(200, 200, 200, 200))
rf_new = rf[m$matches,]
l_new = l[1:length(l) %in% m$matches,]

# test 1
n = 1
plot(l[n,]); plot(rf[n,], add = T) # fail

```r
plot(l_new[n,]); plot(rf_new[n,], add = T) # works
```

![unnamed-chunk-1-3](https://cloud.githubusercontent.com/assets/1825120/20066555/da69703c-a509-11e6-8342-d236ed6f8810.png)


```r
# test 2
n = 3
plot(l_new[n,]); plot(rf_new[n,], add = T) # succeed


# Old tests

# round to nearest 10 m
id1_cols = apply(l_od_coords, 2, round, -2)
id2_cols = apply(rf_od_coords, 2, round, -2)
points(id1_cols[,c("fx", "fy")])
points(id1_cols[,c("tx", "ty")])
points(id2_cols[,c("fx", "fy")])
points(id2_cols[,c("tx", "ty")]) # they match
```

![plot of chunk unnamed-chunk-1](figure/unnamed-chunk-1-4.png)

```r
id1 = apply(id1_cols, 1, paste, collapse = "-")
id2 = apply(id2_cols, 1, paste, collapse = "-")
(new_order = match(id2, id1))
```

```
## [1] NA NA NA NA NA
```

```r
id1 %in% id2
```

```
## [1] FALSE FALSE FALSE FALSE FALSE
```

**Comment by Robinlovelace** [comment]
Also thinking it should be called `line_match` now as it's matching not merging.

**Comment by Robinlovelace** [comment]
Problem: what do you do about lines like `l[1,]` that have no match?

Suggestion: Print the line numbers in `l1` with no match in `l2`.

**Comment by richardellison** [comment]
Do you just want to use origin and destination coordinates to match lines?

Normally when I'm matching lines I typically use [Hausdorff Distance](http://postgis.net/docs/ST_HausdorffDistance.html) in PostGIS or the gDistance function in rgeos because it accounts for differences in the paths of the lines (rather than just origin-destination).

**Comment by Robinlovelace** [comment]
Aha that sounds good, although in our dataset it is the orgin and destination specifically that we're matching to. Interesting that there doesn't seem to be an [implementation for sp objects in R, based on a rudimentary web search](https://www.google.es/search?client=ubuntu&channel=fs&q=+Hausdorff+Distance+R&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=f_IgWKm_AYPY8ge31ITwBg) yet there is [clearly a GEOS algorithm for this](http://geos.osgeo.org/doxygen/classgeos_1_1algorithm_1_1distance_1_1DiscreteHausdorffDistance.html). Any plans for this related to sf/rgeos that you know of @edzer? Wondering where the best place for an R implementation to live would be and guessing rgeos.

Ah OK looking at the docs it seems `hausdorff=TRUE` in `gDistance()` would do the trick, e.g.


```r
library(stplanr)
```

```
## Loading required package: sp
```

```r
r = routes_fast[1:3,]
plot(r,
     col = c("red", "yellow", "green"),
     lwd = 3:1)
```

![](test_files/figure-html/unnamed-chunk-1-1.png)

```r
rgeos::gDistance(r, r, byid = T, hausdorff = T)
```

```
##            1          2          3
## 1 0.00000000 0.01569878 0.01209752
## 2 0.01569878 0.00000000 0.02130649
## 3 0.01209752 0.02130649 0.00000000
```

But why is the difference between 1 and 2, which seem very similar, 0.016 whereas 1 and 3, which seem very different, is only 0.012?

![unnamed-chunk-1-1](https://cloud.githubusercontent.com/assets/1825120/20077246/8a4dd64a-a533-11e6-911c-9eb846742d7f.png)

**Comment by edzer** [comment]
Looks pretty trivial to add to [CPL_geos_binop](https://github.com/edzer/sfr/blob/master/src/geos.cpp#L73)
