### ISSUE TITLE
Interface to the OSRM API

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#14]
And decode the results.

E.g.

http://router.project-osrm.org/viaroute?loc=52.503033,13.420526&loc=52.516582,13.429290&instructions=true

**Comment by richardellison** [comment]
I have made a start on this by adding a function to decode the encoded polylines used for the route geometries returned by OSRM (see #22). I'm thinking the function to decode OSRM results should return a SpatialLinesDataFrame with the route geometries and other data?

**Comment by Robinlovelace** [comment]
Great work - we're most of the way there. Will look at creating `route_osrm` next weekend, unless you get there 1st.

**Comment by Robinlovelace** [comment]
Functionality added.
