### ISSUE TITLE
line_bearing bidirectional returns the same result

### ISSUE THREAD

**Issue by mem48** [ropensci/stplanr#153]
line_bearing(l, bidirectional= T) and line_bearing(l, bidirectional = F) return the same result

```
bearingT =  line_bearing(l, bidirectional= T)
bearingF =  line_bearing(l, bidirectional = F)

bearingT == bearingF
[1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
```

**Comment by Robinlovelace** [comment]
Thanks for reporting.

Another reproducible example, using the example data:

```r
library(stplanr)
lb1 = line_bearing(flowlines, bidirectional = T)
lb2 = line_bearing(flowlines, bidirectional = F)
identical(lb1, lb2) # TRUE
plot(lb1, lb2)
```

![screenshot from 2016-12-01 11-16-22](https://cloud.githubusercontent.com/assets/1825120/20792019/a95540b4-b7b7-11e6-80a7-e0feeb9edfbc.png)

My interpretation: The Y axis should not be negative - an easy fix I think.
