### ISSUE TITLE
Create line_sample function

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#158]
An enhancement of spsample so the frequency of points is proportional to a vector of weights. @edzer - interested if `spsample` was ever planned to have a 'weight` field - that would solve the problem - could look into it if needs be.

**Comment by Robinlovelace** [comment]
This works:

```r
# Aim: create points proportional to some value

#' @examples
l = flowlines[2:5,]
l$All
npoints = 100
p = line_samplepoints(l, 50)
plot(p)
p = line_samplepoints(l, 50, prob = 1:length(l))
plot(p)
line_samplepoints <- function(l, npoints, prob = 1, type = "regular") {
  # divide points between l elements
  if(length(prob) < length(l))
    prob <- rep(prob, length.out = length(l))
  npoints_lines = round(npoints) * prob / mean(prob) / nrow(l)
  uvals = unique(npoints_lines)
  for(i in 1:length(uvals)) {
    line_sel = npoints_lines == uvals[i]
    if(i == 1)
      p = spsample(l[line_sel,], n = sum(npoints_lines[line_sel]), type = type) else
        p = tmap::sbind(p, spsample(l[line_sel,], n = sum(npoints_lines[line_sel]), type = type) )
  }
  p
}



# test spsample
set.seed(99)
p = spsample(l, 100, "regular")
plot(p)
p2 = spsample(l, 100, "regular", prob = c(1, 2, 100, 1000))
plot(p2)

```

**Comment by edzer** [comment]
@Robinlovelace , `sf` now has a `st_line_sample`, which randomly samples a set of  `LINESTRING`s (`sfc`), with density possibly set per element. It returns a `MULTIPOINT` for each `LINESTRING`. Let me know whether it is useful (I might change the name and interface of this function later on.)

**Comment by Robinlovelace** [comment]
Nice - sounds useful and faster than my hacked code above.

We may have to import **sf** sooner than expected!

**Comment by Robinlovelace** [comment]
Quick question: can you do regular sampling, as in the example above?

Please try to reproduce if you get time.

**Comment by Robinlovelace** [comment]
Without variable `prob` field:

![image](https://cloud.githubusercontent.com/assets/1825120/21046403/712cd6b6-bdfc-11e6-91b4-37bca9f3c845.png)

With it as `prob = 1:length(l)`

```r
p = line_samplepoints(l, 50, prob = 1:length(l))
plot(p)
```
![image](https://cloud.githubusercontent.com/assets/1825120/21046436/a008b6a8-bdfc-11e6-90de-25ce21c090ea.png)

**Comment by edzer** [comment]
```
library(sf)
ls = st_sfc(st_linestring(rbind(c(0,0),c(0,1))),
    st_linestring(rbind(c(0,0),c(.2,0))), crs = 4326)
ls = st_transform(ls, 3857)

png("line.png", 800, 800)
par(mfrow = c(2,2))
x = st_line_sample(ls, density = 1/3000)
plot(ls)
plot(x, add = TRUE, col = 'red')

x = st_line_sample(ls, density = c(1/3000, 1/1000))
plot(ls)
plot(x, add = TRUE, col = 'red')

x = st_line_sample(ls, density = 1/3000, "random")
plot(ls)
plot(x, add = TRUE, col = 'red')

x = st_line_sample(ls, density = c(1/10000, 1/1000), "random")
plot(ls)
plot(x, add = TRUE, col = 'red')
```
![line](https://cloud.githubusercontent.com/assets/520851/21047057/2426154c-be08-11e6-87d5-d136f0ca4103.png)

**Comment by Robinlovelace** [comment]
Great work!

**Comment by Robinlovelace** [comment]
Makes my code redundant though :( hehe

**Comment by edzer** [comment]
It's still unresolved how to do this
* for `MULTILINESTRING` geometries, and
* for lines on the sphere (longlat coordinates; the GDAL function I use does not provide this, geosphere also seems not to, but has `gcIntermediate`)

**Comment by Robinlovelace** [comment]
Good to know - it's a pretty good start though. Solid - would you like me to do some benchmarks on this, e.g. in `sfr/tests/benchmarks/st_sample.R`?

**Comment by edzer** [comment]
Your benchmark will not affect what I do in this particular case. I was more curious whether you can get around with the `MULTIPOINT` geometries that come out.

**Comment by Robinlovelace** [comment]
As long as they can go back into a `SpatialPoints` object that should be fine - this is the kind of application we're aiming for btw, potentially to present to the UK's Department for Transport and then hopefully go international.

**Comment by Robinlovelace** [comment]
On a slightly different note, @mem48 is looking at the direct line to raster option but it's being slow on the giant files we have. Any ideas what the timeline is on C implementation of that in **raster**?

**Comment by edzer** [comment]
Are you looking at doing this with the raster package?

**Comment by mem48** [comment]
@edzer Yes, but the performance is very poor.

We have lines which represent people traveling to work along the road network, each line has a value for the number of people.

We would like to rasterize those lines with the value of number of people. So we would have  a kind of heat map showing busy and quite roads. (See example image, n.b. this also shows a base map)

![sample](https://cloud.githubusercontent.com/assets/15819577/21050949/abbf6aaa-be15-11e6-840f-647f53a5ff40.png)

The problems we are having are:

1) If two lines overlap we would like to sum the number of people, rasterize only takes one value per cell.
 We solve this by creating groups of non-overlapping lines, and rasterizing each group separately, then added the rasters together
2) Due to the large nature of the dataset (about 4 million lines) we end up with many groups (around 5000) each covering the whole of England. To create the raster for one group takes around 45 min, so the total process would take around 150 days!

I had looked at using gdalUtils::gdal_rasterize which was faster but I couldn't get it to work reliably.
I also looked at a new package velox which claims to be 35x faster than raster but currently only rasterizes polygons and not lines.

**Comment by edzer** [comment]
Note that gdal_rasterize is now part of GDAL's C++ [api](http://www.gdal.org/gdal__utils_8h.html#afd3a6dead8773c7716e2a4cbaa4e8d4e), since gdal 2.1.

**Comment by mdsumner** [comment]
@mem48 @Robinlovelace do you have an example for the rasterize slowness? I've been doing exactly this for fisheries impacts, we use raster's cell abstraction to build a "cell index" pool and usually spatstats::pixellate for the local rasterization itself, it's adaptable to direct sums like "time along line" or line intersection counts, and specifically for us repeated impacts within a local cell.  Also, cellFromLine is probably fine if density and tricky weighting isn't required.  I never actually instantiate the entire high resolution raster,  which is suggested by your 45min creation time, so was thinking that might help here.

**Comment by Robinlovelace** [comment]
Very interesting - imagine Malcolm will be keen - hope is to eventually implement what we did (on 4 million routes using the HPC cluster) in a function and it sounds like your approach could be useful.
