### ISSUE TITLE
Automated testing is down

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#16]
https://travis-ci.org/Robinlovelace/stplanr

@sckott can you assist with this?

**Comment by sckott** [comment]
Yep. Un momento

**Comment by sckott** [comment]
https://travis-ci.org/ropensci/stplanr builds working

**Comment by Robinlovelace** [comment]
Thanks for the fast fix @sckott

**Comment by sckott** [comment]
np!
