### ISSUE TITLE
Transition to using sf

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#175]
- [x] import **sf** in next version and use internally
- [x] allow **sf** objects to be used as inputs
- [ ] remove **rgdal** and **rgeos** dependencies

Eventually I think the default class for spatial data in **stplanr** should be based on **sf**. This does not have to happen quickly. We can start using **sf** internally, as shown here   but converting back to **sp** classes before returning the object.

Eventually, when **sf** is expected, we could convert **sp** objects into **sf** objects at the outset like this:

```r
if(is(x, "Spatial")) {
  x = sf::st_as_sf(x)
}
```

Sound like a good approach @edzer and @richardellison?

**Comment by richardellison** [comment]
I'll have to spend a bit more time becoming familiar with sf. With use rgeos quite extensively at the moment so we'll probably need to make a fair number of changes to remove it as a dependency at this point.

Suggest we open another branch to work on switching to sf for the time being just in case we run into difficulties somewhere.

**Comment by Robinlovelace** [comment]
Agreed - will take a while. Suggest we use this as the development branch with sf dependencies for testing (will be good to see if this works with ``rhub::check_windows()`): https://github.com/ropensci/stplanr/pull/164

**Comment by mpadge** [comment]
Having actually used `stplanr` for real for the first time to do the [`bikedata` vignette](https://mpadge.github.io/bikedata/articles/bikedata.html), i can only agree that this is an important transition. This is particularly because `sf` is simply so much faster, including via `osmdata_sf()` vs `osmdata_sp()`. The `bikedata` example is kinda slow because of `_sp()` necessity, but would be around 10 times faster with `_sf()`, if that were compatible with `stplanr`. More than happy to offer any assistance I can!

**Comment by Robinlovelace** [comment]
Awesome, thanks for that offer Mark. Coincidentally Richard and I have discussed this today and also want to prioritise it, after vital issues such as the [website](https://ropensci.github.io/stplanr/) are fixed of course ;)

**Comment by mpadge** [comment]
i'm sure you guys have got this in mind, but just to put it explicitly out there: `sf` adaptation ought to end up ... hmm, what do we call this? ... "R spatial agnostic"? You ought to be able to simply thrown an `R` spatial object, whether `sp` or `sf` at any routine, and it ought to behave the same. It's much easier at the outset to avoid writing new "@export"-ed functions for `sf` - just put a check and pass `sf` objects to new (non-exported) sub-function.

Note also for future discussions, and general positioning in the larger `R` scheme-o-things: This approach quite directly contradicts hw's single-type ethos, yet is i would argue both necessary and clearly superior. Just good to keep in the mind that the current `sp/sf` dichotomy presents a very strong case for diverging from one of the currently more prominent approaches to `R` coding. `sp` output is going to be with us for years to come, so we will need functions that both accept and return appropriate yet non-single types for an equivalently long time to come.

**Comment by edzer** [comment]
Agreed, but it's also a burden, and clutters code. 

How large is the user base of stplanr? If its users are tidyverse people, they will not mind a small change in API if it's for a good cause.

**Comment by Robinlovelace** [comment]
The user base is still quite small (10k [downloads](https://cranlogs.r-pkg.org/badges/grand-total/stplanr) in total so far) so slight changes to the API will have less of an impact than in pkgs like `dplyr` and (now it's hit the big-time) `sf`.

We've kept the version numbers very low to show that to some extent this is an experimental pkg to demonstrate that you *can* do transport planning with R.

I think a substantial refactoring of the API, using aliases to keep backwards compatibility, is the best way forward. I would like all geographic functions (e.g. `buff_geo`) to start with the same letters, so we end up with all function names adhering to a naming convention such as:

- `geo_*()` geographic functions
- `od_*()` functions on od data
- `route_*()` route data, allocated to the route network
- `line*_()` or `seg_*() or both functions for doing things with lines and/or segments of routes.

The paper that explains the thinking underlying **stplanr** is under review. When the review comes back that will be an ideal opportunity to implement some of these ideas but I would like to hear back from others who know more about creating useful, maintainable R packages than I do before proceeding with this campaign.

This, I imagine, will follow the dependency culling campaign exemplified by https://github.com/ropensci/stplanr/pull/196 .

In any case advice on the best way forward greatly appreciated and I think supporting both sf and sp for now is the best plan. One question: should we use methods to keep the code base for sp and just add something like `function_name.sf()` to support these new fangled simple feature things?

Thanks loads for the input.

**Comment by richardellison** [comment]
I agree that ideally all functions should support both and that has been my approach with #199 but it does make for more convoluted code.

**Comment by edzer** [comment]
Using generics is a good way out of getting code clutter.

**Comment by Robinlovelace** [comment]
Closing for now - we don't need to remove the **rgeos** dependency - can happen gradually...
