### ISSUE TITLE
Make pkgdown site

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#176]
Like this: https://hadley.github.io/pkgdown/

**Comment by mpadge** [comment]
robin, i'm pretty sure i can safely announced that `pkgdown` is now free of the former problems that arose with the dev version of `devtools`. I used it last week for [`bikedata`](https://mpadge.github.io/bikedata/) and it worked like a charm. The whole process took less time than a standard `R CMD check`. Just go ahead a do it, i say ... (just adapt a `_pkgdown.yml` first, from one of maelle's or my repos.)

**Comment by mpadge** [comment]
@Robinlovelace - you need to edit the repo description and paste in the url (https://ropensci.github.io/stplanr/) to the `pkgdown` page

**Comment by Robinlovelace** [comment]
Cheers for the heads-up Mark - I've added the description here to here in the README website - is that what you meant?

**Comment by mpadge** [comment]
nup, but the url is there now regardless, so it's all okay. I meant just clicking the "Edit" button at top right of the main repo page and pasting in the git page address, which it seems you did already. Nice! Take it from me: That makes `stplanr` far easier to use!

**Comment by Robinlovelace** [comment]
Aha good stuff - now we can get on with all the refactoring.

Liking how fast sf is LINESTRING list col representing 18k roads with 200 variable plotted in an instant:

![image](https://user-images.githubusercontent.com/1825120/26836256-47958d1c-4ad2-11e7-80ed-9cd6c69a3ca9.png)
