### ISSUE TITLE
dist_google Error when using addresses with spaces

### ISSUE THREAD

**Issue by richardellison** [ropensci/stplanr#184]
I noticed this when I was trying to retrieve a distance matrix using addresses instead of coordinates with the dist_google function:

```{r}
dist_google(from="1 Glebe Point Road, Sydney, NSW", to="1 Circula Quay, Sydney, NSW")
```
Results in the follwing:
```{r}
Sent this request: https://maps.googleapis.com/maps/api/distancematrix/json?units=metric&origins=1 Glebe Point Road, Sydney, NSW&destinations=1 Circula Quay, Sydney, NSW&mode=bicycling

Error in open.connection(con, "rb") : HTTP error 400. 
```

Seems all that is needed to fix this is to encode the URL to replace spaces with %20.

@Robinlovelace I would fix this myself, but not sure if you want to change it when you're adding some warning/error messages to the function to address #182 ?

**Comment by Robinlovelace** [comment]
Thanks Richard - added to the lengthening 'to-do' list!
