### ISSUE TITLE
stplanr broken with CRAN dplyr

### ISSUE THREAD

**Issue by rsbivand** [ropensci/stplanr#210]
The dplyr release to [CRAN](https://cran.r-project.org/web/checks/check_results_stplanr.html) has caused havoc - I guess you'd need to condition on dplyr version.

**Comment by Robinlovelace** [comment]
Yes - I believe this is the same as #189

**Comment by rsbivand** [comment]
It is a weakness of tidyverse that they dictate breaking changes. It would be much less destructive if they permitted slower-moving reverse dependencies to stay on an earlier stable version, as much software does. This is cathedral, not bazaar ... and it is going to harm tidyverse, people will give up on a constantly moving target.

**Comment by Robinlovelace** [comment]
If it continues to move. Hadley has said sorry for breaking stuff and I suspect things will settle down now that tidyeval is allowing people to write code that is more concise and explicit (in the potentially unlikely event that they actually understand it!).

Best tidyeval resource I've seen: https://cran.r-project.org/web/packages/dplyr/vignettes/programming.html

But yeah longer time-scales and phased approach would be good, especially in summer now many people are on holiday (from Barcelona)!

**Comment by Robinlovelace** [comment]
I think this is fixed now - 2 [tests](https://cran.r-project.org/web/checks/check_results_stplanr.html) on 0.1.9 so far are passing:

![image](https://user-images.githubusercontent.com/1825120/28140375-07e6d064-6750-11e7-8bd2-4e617890feec.png)
