### ISSUE TITLE
get bb2poly to return actual bounding polygons?

### ISSUE THREAD

**Issue by mpadge** [ropensci/stplanr#219]
Just a thought, but now this has been implemented in [`osmdata::getbb(..., format_out = "polygon")`](https://github.com/ropensci/osmdata/blob/master/R/getbb.R) it would also be trivial to do it with `stplanr`. If you saw a use case.

**Comment by Robinlovelace** [comment]
+1

**Comment by Robinlovelace** [comment]
Closing for now, would be good to do, but not a priority.
