### ISSUE TITLE
installation instructions on mac os sierra

### ISSUE THREAD

**Issue by tbuckl** [ropensci/stplanr#245]
i found these instructions worked for me:

https://stackoverflow.com/questions/38231896/r-unable-to-install-rcpp-package-for-r-3-3-1-on-osx-el-capitan#38233468

**Comment by tibbl35** [comment]
whoops i spoke to soon...

**Comment by Robinlovelace** [comment]
This sounds like an issue with installing packages that `stplanr` depends on such as `sf` or `Rcpp` so closing for now. I suggest reading the documentation there.

**Comment by Robinlovelace** [comment]
Here's some documentation on how to install sf - you'll find similar info on the Rcpp github page: https://github.com/r-spatial/sf#simple-features-for-r Hope this helps, let me know if not!

**Comment by tibbl35** [comment]
thanks @Robinlovelace those instructions on how to install sf are good.

**Comment by tibbl35** [comment]
@Robinlovelace i eventually gave up when it came to rigraph. i think my `rcpp` problems were resolved with the notes in the link above.

**Comment by tibbl35** [comment]
@Robinlovelace i'll post back here when i get the `igraph` install resolved. excited to use the package. thanks for your help!

**Comment by Robinlovelace** [comment]
Thanks for posting, let us know how you get on, and feel free to re-open if you find any other issues.

**Comment by layik** [comment]
I think X11Quartz needs to be installed as documented by r-base people @Robinlovelace. Once I installed X11 Quartz I was able to install `stplanr`. Do not want to reopen the issue.
https://cran.r-project.org/bin/macosx/

> Note: the use of X11 (including tcltk) requires XQuartz to be installed since it is no longer part of OS X. Always re-install XQuartz when upgrading your macOS to a new major version.

**Comment by Robinlovelace** [comment]
Does this solve it @layik  https://github.com/ropensci/stplanr/commit/ca857c767f77818abc06aefa501c2b40d5b13663

**Comment by layik** [comment]
Yep that hopefully is enough @Robinlovelace.

**Comment by Robinlovelace** [comment]
Thanks for the input - will re-compile this Rmarkdown document soon. More here on this strange md-R mixed format FYI Layik: https://rmarkdown.rstudio.com/
