### ISSUE TITLE
Function to convert cyclestreets output to multiline

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#250]
At present you get a single `SpatialLinesDataFrame` from `route_cyclestreet()`. It would be beneficial to have ~~an sf MULTILINESTRING~~  sf linestrings returned with attributes per segment. Example .json attached.

Code (needs CYCLETREET defined in .Renviron):

```r
stplanr::route_cyclestreet("Berlin", "Potsdam", silent = F)
```
[journey.json.zip](https://github.com/ropensci/stplanr/files/1898939/journey.json.zip)

Heads-up @EricKrg + heads-up @mvl22

**Comment by Robinlovelace** [comment]
This should get you the full JSON:

```r
res_json = stplanr::route_cyclestreet("Berlin", "Potsdam", silent = FALSE, save_raw = TRUE)
```

**Comment by Robinlovelace** [comment]
OK that's easy to change and `route_cyclestreets()` works. In any case, in terms of actually doing it, here's some working code I put together on the train journey to Nuremberg: https://github.com/Robinlovelace/stplanr/blob/f5820dc1a604e98d340424eee06d2c6c6c5a751e/R/json2sf_cs.R

@EricKrg pls tak a look at that and see if you can reproduce it. I think segment-level results could be useful for many applications. Note the `sf` object creation works but I've not populated the data frame with many variables yet, just busynance and the segment name. Question for @mvl22: there seems to be one more name than there are segments because the first `points` object is NA - one to discuss in Leeds on the course, among many other things!

**Comment by Robinlovelace** [comment]
Also worth noting this is an excellent resource for figuring out what's in the output from the routing API: https://www.cyclestreets.net/api/v1/journey/

**Comment by EricKrg** [comment]
Hey @Robinlovelace  your example worked fine for me. I used your code to add more variables to the multi-segment linestring (with optional crs, as well as optional variables):

_I hope that was what you expected_
```r
json2sf_cs <- function(obj, cols, default_crs) {
  coord_list = lapply(obj$marker$`@attributes`$points[-1], txt2coords)
  rsflx = lapply(coord_list, sf::st_linestring)
  rsfl = sf::st_sfc(rsflx)
  
  # variables 
  # useful cols: busynance, name, elevations, distances, turn,provisionName
  
  b = sapply(obj$marker$`@attributes`$busynance[-1], as.numeric)
  n = obj$marker$`@attributes`$name[-1]
  e = stringr::str_split(obj$marker$`@attributes`$elevations[-1],pattern = ",") %>%
      lapply(as.numeric) %>%
      lapply(mean) %>%
      unlist()
  d = sapply(obj$marker$`@attributes`$distance[-1],as.numeric)
  t = obj$marker$`@attributes`$turn[-1]
  p = obj$marker$`@attributes`$provisionName[-1]
  
  d = data.frame(busynance = b, name = n, elevations = e, distance = d,
             turn = t, pname = p)
  
  # todo: create more segment-level statistics (vectors) +
  # add them to the data frame (d) below
  if(!missing(cols)){
    d = d[,cols]
  } 
  else {
    d 
  }
  
  rsf = sf::st_sf(d, geometry = rsfl, crs = if(default_crs){4326}else{NA})
  
  return(rsf)
  
}
# test calls
#json2sf_cs(res_json,default_crs = T)
#json2sf_cs(res_json,default_crs = F, cols = c("distance", "turn","name","busynance"))
```

**Comment by EricKrg** [comment]
@Robinlovelace just did it, yes it is the first! 😀

**Comment by Robinlovelace** [comment]
Great but I cannot see the PR... I plan to merge the original implementation in the master branch on this repo, that will make it simpler.

**Comment by Robinlovelace** [comment]
Heads-up @EricKrg - after discussion with @mvl22 yesterday I've decided to split-out `route_cyclestreets` into a new package: https://github.com/Robinlovelace/cyclestreets Following the 'unix philosophy' this will make **stplanr** more modular. When it's on CRAN stplanr can import it and the `route_cyclestreets` functions will be depreciated. Sound like a plan? Please continue dev work here https://github.com/Robinlovelace/cyclestreets and remind me to add you to the contributors list!

**Comment by mvl22** [comment]
Awesome! Hope we can make this an official package within github.com/cyclestreets in due course :)

**Comment by Robinlovelace** [comment]
Contributions welcome and yes happy to port it although if we want peer review + exposure hosting on ropensci is also a strong option - could always have the dev branch on cyclestreets.

**Comment by EricKrg** [comment]
Hey @Robinlovelace  i opened a PR for this conversion fun a while ago, is this now obsolete with the new package?

**Comment by Robinlovelace** [comment]
Hey @EricKrg yes the function `cyclestreets::journey()` now includes the new variables, and much more. Please give it a test and let me know how you get on. BTW I couldn't find the PR. There is some stuff that needs fixing in the new repo - let me know if you're interested in helping and I'll point you in the right direction. Closing this issue assuming you can install and test the new repo (please let me know if it works).

**Comment by EricKrg** [comment]
@Robinlovelace  the new pckg worked fine for me. I am definitely interested in contributing! 

PS.: im a bit busy with university the next two weeks but i'll try my best.

**Comment by Robinlovelace** [comment]
OK no worries, only work on it to the extent that it's fun, interesting + useful. I will add an issue that you may be able to help with and ping you. Many thanks - you actually instigated all this so you've contributed already!
