### ISSUE TITLE
Compilation check warning

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#260]
`devtools::check()` generates this warning:

```
Status: 1 WARNING
checking compilation flags used ... WARNING
Compilation used the following non-portable flag(s):
  ‘-Wdate-time’ ‘-Werror=format-security’ ‘-Wformat’
```

Any ideas how to fix this @richardellison ?

**Comment by mpadge** [comment]
That's local only and won't affect CRAN. Try `rhub` to confirm

**Comment by Robinlovelace** [comment]
Have done re. `rhub` - real useful tests. Thanks for the heads-up, confirmed that 0.2.5 is now up on CRAN. Lots more to do but wanted to get that bug fix / maintenance release out before tackling chunkier issues like those mentioned in #257 . Closing for now!
