### ISSUE TITLE
Function to create 'road buffers' around points

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#265]
To be called `road_buffer()` or similar it will take a series of points and a road network and then create a polygon for each point representing the part of the road network close to it. Useful for crash analysis, as discussed with @jimuttley.

**Comment by sandrews-CTPS** [comment]
If you form voronoi polygons using something like, sf::st_voronoi(), it would give you the option to indicate if crashes (or other "events") are closer to one intersection or another if the intersections are close. I don't think you'd walays want it to return these in case you merely cared about whether your event is within a distance of the intersection.

@andybega wrote this function: https://github.com/andybega/r-misc/blob/master/spatial/marked-points-to-polygons.R to attach ids to the voronoi polygons. I was able to use it to assign road segments within a crow-flies buffer to bus stops.

**Comment by Robinlovelace** [comment]
Very interesting. Hoping to get on this next week, thanks for the input.

**Comment by Anyaoha** [comment]
Would this be same as having a buffer around a particular point regardless if it's in a road network. Take a look at the rgeos package if that helps
