### ISSUE TITLE
Support SUMO

### ISSUE THREAD

**Issue by harryprince** [ropensci/stplanr#284]
hi stplanr team,
   As your mention as the [stplanr paper](https://cran.r-project.org/web/packages/stplanr/vignettes/stplanr-paper.html), integrating stplanr with  SUMO, MATSim and MITSIMLAB is the next direction.
    Does anyone get interested in this topic? Currently, I am focusing on microscopic simulation and bike-sharing economics.

**Comment by harryprince** [comment]
Currently, sumopy is very bugy under python2.7, maybe shiny is a better option to build the web interface for SUMO.

**Comment by Robinlovelace** [comment]
Hi @harryprince I'm interested in this for sure and think that an R interface to SUMO is a logical next step for making R a stronger environment for transport planning. Such a project could build on the experience of other R interfaces to external programs, such as:

- [nlrx](https://github.com/ropensci/nlrx), which provides an R interface to netlogo
- [tensorflow](), which provides an R interface to [tensorflow](https://github.com/rstudio/tensorflow)

The second one provides a function, `tensorflow::install_tensorflow()` to even do the installation. I think a function `install_sumo()` would be possible and desirable.

A key concept in software design that I learned late is modularity. I Therefore propose that code that provides this interface should be put in a separate repo and R package. If it works, we can add it to the `Suggests` or even `Imports` in `stplanr`. The only questions in my mind are who should lead this effort and where should the repo live? I'm happy to know of demand for this and would like to support with the development of a `sumor` (or similarly/better named!) package.

**Comment by harryprince** [comment]
nlrx or [SpaDES](https://github.com/PredictiveEcology/SpaDES/issues) interface is currently that I found in R for spatial simulation tools. However, the interface of these tools are not tidy, and maybe we need to list the `modularity` and process before we get started.

[aimsun](https://www.aimsun.com/aimsun-next/editions/) and [ptv group](http://ptvgroup.com) are the leading company in transportation simulation which integrated microscopic and macroscopic simulation all in one. Maybe we can learn more about these advanced commercial softwares.

**Comment by Anyaoha** [comment]
@harryprince I think techniques of routing and plotting of routes can be learned from [http://ptvgroup.com/]  ptv group. 
I am also interested in this topic because I am looking for a better and easy way of plotting vehicle routes on a map in R because I have the co-ordinates of the locations. 
So I would want to plot routes from a location through to other locations and back to the origin

**Comment by harryprince** [comment]
here is the possible `sumor` project structure:

SUMO: command line simulation
GUISIM: simulation with a graphical user interface
NETCONVERT: network importer
NETGEN: abstract networks generator
OD2TRIPS: converter from O/D matrices to trips
JTRROUTER: routes generator based on turning ratios at intersections
DUAROUTER: routes generator based on a dynamic user assignment
DFROUTER: route generator with use of detector data
MAROUTER: macroscopic user assignment based on capacity functions
NETEDIT: Visual editor for street networks, traffic lights, detectors, and further network elements
TraCI: online interaction with the simulation
SUMOPy: a tool by Joerg Schweizer supporting the whole SUMO toolchain with a GUI especially for demand modelling
Cadyts: Calibration of Dynamic Traffic Simulations between SUMO and MATSIM

**Comment by Robinlovelace** [comment]
Heads-up @harryprince, I've created package here - on this org because @mpadge has expressed interest and it's our joint GH space / organisation. Can add you as a collaborator if you'd like. One question: please test the `install_SUMO()` function - does it work for you? Needs some work: it provides instructions on how to install SUMO but doesn't actually install it which is fine IMO. But should work on Windows. reprex on my machine: 

``` r
devtools::install_github("ATFutures/sumor")
#> Downloading GitHub repo ATFutures/sumor@master
#>   
   checking for file ‘/tmp/Rtmp6PAjQN/remotes2a2f35bcfd64/ATFutures-sumor-c0a6374/DESCRIPTION’ ...
  
✔  checking for file ‘/tmp/Rtmp6PAjQN/remotes2a2f35bcfd64/ATFutures-sumor-c0a6374/DESCRIPTION’ (790ms)
#> 
  
─  preparing ‘sumor’:
#> 
  
   checking DESCRIPTION meta-information ...
  
✔  checking DESCRIPTION meta-information
#> 
  
  
  
   
  
   checking for LF line-endings in source and make files and shell scripts
  
─  checking for LF line-endings in source and make files and shell scripts
#> 
  
  
  
─  checking for empty or unneeded directories
#> ─  building ‘sumor_0.0.0.9000.tar.gz’
#> 
  
   
#> 
#> Installing package into '/home/robin/R/x86_64-pc-linux-gnu-library/3.5'
#> (as 'lib' is unspecified)
    sumor::install_SUMO()
#> To install sumo in Ubuntu, please add the ppa with:
#> sudo add-apt-repository ppa:sumo/stable
#> sudo apt-get update
#> sudo apt install sumo
#> To build from source, see:
#> https://github.com/eclipse/sumo#build-and-installation
```

<sup>Created on 2019-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by Robinlovelace** [comment]
Note: I'm currently building it from source. Any experience installing it on Windows?

**Comment by Anyaoha** [comment]
@Robinlovelace I just ran the install package for sumor `devtools::install_github("ATFutures/sumor")` and I think it installed on R studio in windows. But it seem to be at it's infancy stage as you said. Let me know in ways I can help. 


`devtools::install_github("ATFutures/sumor")
Downloading GitHub repo ATFutures/sumor@master
√  checking for file 'C:\Users\Public\Documents\Wondershare\CreatorTemp\RtmpWMzgXi\remotes3a28eb82ad3\ATFutures-sumor-7498073/DESCRIPTION' ...
-  preparing 'sumor':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'sumor_0.0.0.9000.tar.gz'
   
Installing package into ‘C:/Users/Uche/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'sumor' ...
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'sumor'
    finding HTML links ... done
    install_SUMO                            html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (sumor)
In R CMD INSTALL`

**Comment by Anyaoha** [comment]
@Robinlovelace  I just ran the install package for sumor `devtools::install_github("ATFutures/sumor")` and I think it installed on R studio in windows. But it seem to be at it's infancy stage as you said. Let me know in ways I can help.

`devtools::install_github("ATFutures/sumor")
Downloading GitHub repo ATFutures/sumor@master
√  checking for file 'C:\Users\Public\Documents\Wondershare\CreatorTemp\RtmpWMzgXi\remotes3a28eb82ad3\ATFutures-sumor-7498073/DESCRIPTION' ...
-  preparing 'sumor':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'sumor_0.0.0.9000.tar.gz'
   
Installing package into ‘C:/Users/Uche/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'sumor' ...
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'sumor'
    finding HTML links ... done
    install_SUMO                            html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (sumor)
In R CMD INSTALL`

**Comment by Robinlovelace** [comment]
Heads-up @Anyaoha the package is no where near ready. One thing that would help: small (<1 MB) example input datasets and SUMO commands you'd like to run on them.

**Comment by Anyaoha** [comment]
@Robinlovelace okay. I'd be ready to help if you need me. :)

**Comment by Robinlovelace** [comment]
Great. If you can create a scenario with input data that can form the basis of a SUMO simulation, that would be great. I've created an issue here, where this can be discussed: https://github.com/ATFutures/sumor/issues/3

**Comment by harryprince** [comment]
Hi Robin,
    I added a Windows/Mac OS installation branch at GitHub. Wish to discuss
more module design at repo issue or gitchat.

Best Regards,
Harry Zhu

**Comment by Robinlovelace** [comment]
Great. Many thanks.
