### ISSUE TITLE
Make travis autodeploy website

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#287]
Heads-up @sckott and @maelle I'm trying to set this up but get the following message:

```
travis::use_travis_deploy()
Authenticating with GitHub
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Authenticating with GitHub
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error: Must have role admin to edit organization ropensci, not member
```

**Comment by maelle** [comment]
Yeah see https://github.com/ropenscilabs/travis/issues/95 Either try the workaround mentioned there or ping tomorrow (am AFK) and I'll add the keys from my account. Sorry.

**Comment by Robinlovelace** [comment]
Thanks for the quick response @maelle, glad to see it's on the radar.

FYI I've tried running this, the code in `tic`, line-by-line:

```r
remotes::install_github("ropenscilabs/tic")
library(travis)
library(tic)
path = "."
info = github_info(path)
repo = github_repo(info = info)
travis_repo = repo
key <- openssl::rsa_keygen()  # TOOD: num bits?

# encrypt private key using tempkey and iv
pub_key <- get_public_key(key)
private_key <- encode_private_key(key)

# add to GitHub first, because this can fail because of missing org permissions
title <- paste0("travis+tic", if (repo == travis_repo) "" else (paste0(" for ", repo)))
github_add_key(pub_key, title = title, info = info)

travis_set_var("id_rsa", private_key, public = FALSE, repo = travis_repo)

message("Successfully added private deploy key to ", travis_repo,
        " as secure environment variable id_rsa to Travis CI.")

}

get_public_key <- function(key) {
  as.list(key)$pubkey
}

encode_private_key <- function(key) {
  conn <- textConnection(NULL, "w")
  openssl::write_pem(key, conn, password = NULL)
  private_key <- textConnectionValue(conn)
  close(conn)
  
  private_key <- paste(private_key, collapse = "\n")
  
  openssl::base64_encode(charToRaw(private_key))
```

Time will tell if it works!

**Comment by Robinlovelace** [comment]
Heads-up @maelle - still failing I'm afraid: https://travis-ci.org/ropensci/stplanr/jobs/508469073#L2087

**Comment by mpadge** [comment]
How did you get this deploying when `travis::use_travis_deploy()` still fails? I'd like to copy all this over to my rOpenSci repos, but need to be able to deploy. I've got everything else working, including deploying on just one travis matrix entry! :tada:

**Comment by maelle** [comment]
> including deploying on just one travis matrix entry!

This, plus deploying without `tic`, is something we should probably add to the dev_guide, so feel free to make a PR to the dev branch of https://github.com/ropensci/dev_guide (in pkg_building.Rmd) with a link to one config file.

**Comment by mpadge** [comment]
Yeah, coz it took me bloody ages to figure it out, and the official travis guidelines do not seem to work here! I shall do that ...

**Comment by maelle** [comment]
I copied the setup from RStudio repos, but yeah it should be in our guidance.

**Comment by mpadge** [comment]
Yeah, that's where I look for guidance in the end, but those are contrary to "official" travis recommendations, so there's obviously something going on ...

**Comment by Robinlovelace** [comment]
Fixed for my use case but yeah there should be a good process for this. Happy to help work that out and be a guinea pig :mouse:
