### ISSUE TITLE
Interested in beta testing rOpenSci pkgdown template?

### ISSUE THREAD

**Issue by maelle** [ropensci/stplanr#291]
If so, here's the guidance (also in need of beta testers so maybe not clear enough!) https://ropenscilabs.github.io/rotemplate/

Any feedback welcome here/ via https://github.com/ropenscilabs/rotemplate

**Comment by Robinlovelace** [comment]
Sure.

**Comment by Robinlovelace** [comment]
One issue: seems the site is not updating: https://ropensci.github.io/stplanr/

**Comment by maelle** [comment]
After commits?

Do you want me to make a PR adding the pkgdown config?

**Comment by maelle** [comment]
I found the problem, you still had master/docs as source for the website, I changed it to gh-pages in the settings of the repo.

**Comment by maelle** [comment]
E.g. now I see Mark listed in https://ropensci.github.io/stplanr/authors.html so all is well :smile_cat:

**Comment by Robinlovelace** [comment]
Aha. Many thanks @maelle thanks for debugging my old, rusty deploy code!

**Comment by Robinlovelace** [comment]
Works: 
![image](https://user-images.githubusercontent.com/1825120/54683118-c1843780-4b08-11e9-9521-6f457625540d.png)

I think the light blue/white is a bit weird though...

**Comment by maelle** [comment]
Yeah I see that and don't understand where it comes from, I need to investigate. It's not on other package websites, and even not in the other pages of stplanr, so it's weird.

**Comment by maelle** [comment]
E.g. the navbar of https://ropensci.github.io/stplanr/articles/stplanr.html is ok

**Comment by Robinlovelace** [comment]
There's always one!

**Comment by maelle** [comment]
That's why I'm glad for beta-testing, and thankful for your accepting the template!

**Comment by maelle** [comment]
I suspect it's due to the leaflet map, but don't have a solution yet.

**Comment by Robinlovelace** [comment]
I concur. I've seen the .js in leaflet mess up other things. I'm happy with it for now but may switch back to boring grey at some point!

**Comment by maelle** [comment]
I've asked for help: https://community.rstudio.com/t/leaflet-in-readme-rmd-breaking-pkgdown-homepage-styling/26619

**Comment by maelle** [comment]
No need to go back to boring grey, the template was fixed thanks to @Rlesur! I rudely re-launched a build on Travis, your website looks fine now (I think?)!

**Comment by Robinlovelace** [comment]
Many thanks!
