### ISSUE TITLE
Rename intro vignette "stplanr.Rmd"?

### ISSUE THREAD

**Issue by maelle** [ropensci/stplanr#292]
This way it'll show up as "Get started" in the navbar of the pkgdown website, see https://pkgdown.r-lib.org/articles/pkgdown.html#navigation-bar (I was told the tip yesterday for https://r-hub.github.io/rhub/)

**Comment by Robinlovelace** [comment]
Sounds reasonable to me.

**Comment by Robinlovelace** [comment]
Great news @maelle, it works! 
![image](https://user-images.githubusercontent.com/1825120/54681655-d363db80-4b04-11e9-8e9a-0a4942047105.png)
