### ISSUE TITLE
Migrate CycleStreets API to V1 version

### ISSUE THREAD

**Issue by mvl22** [ropensci/stplanr#3]
The library currently uses an early format version of the V2 API:
https://github.com/Robinlovelace/stplanr/blob/master/R/gFlow.R#L99
which was available to Robin Lovelace by special arrangement.

However, this format is not the final version which is being finalised, and so is liable to stop working at some point soon. (We don't yet have a date for the finalisation of this V2 API call due to other engineering currently going on - we'd strongly prefer migration to V1 at the moment, to ensure no users of the library rely on current V2 stuff.)

This ticket is a task to migrate to the supported V1 API format - should be fairly simple to change.
http://www.cyclestreets.net/api/v1/journey/

e.g.

http://www.cyclestreets.net/api/journey.json?key=registeredapikey&itinerarypoints=0.117950,52.205302,City+Centre|0.131402,52.221046,Mulberry+Close|0.147324,52.199650,Thoday+Street&plan=quietest

(using the real key rather than ```registeredkey```).

Sorry for the hassle on this.

**Comment by Robinlovelace** [comment]
Hi Martin, it did change but V2 seems operational after some changes: https://github.com/Robinlovelace/stplanr/commit/ca7c7cc4bd08c0b4e91ae564fbbad99cb24f194b

Please do let me know if there are any further dramatic changes but, as you say, it will be easy to migrate to V1 or to update behaviour for V2 if needs be so putting this on hold atm.

**Comment by Robinlovelace** [comment]
Closed by https://github.com/Robinlovelace/stplanr/commit/e86b22d0ffb552a843a6dfb4519900bb83b083f8
