### ISSUE TITLE
route_dodgr, stplanr

### ISSUE THREAD

**Issue by yairlevy** [ropensci/stplanr#305]
Dear,

The help file of function route_dodgr from package stplanr mentions that,

colnames(pts) = c("X", "Y")

These column names should be lower cases, not only for the example to work, but also for the function to work with its pts object in input.

Instead, use:

colnames(pt) = c("x", "y")

Kind regards,

Yaïr Levy
Senior GIS consultant

**Comment by mpadge** [comment]
Thanks @yairlevy - the function works fine whether upper or lower case, but your input here nevertheless served to highlight that the example for that function should actually have had these lines commented out, as they are only needed to recreate the package's `osm_net_example` data. [This PR](https://github.com/ropensci/stplanr/pull/306) has fixed that - thanks!
