### ISSUE TITLE
Issue with sf + travis

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#312]
See https://travis-ci.org/ropensci/stplanr/builds/534102808#L1464

Heads-up @edzer in case of interest. If you know a quick a fix, please let me know (I've not researched this in any detail, may be my Travis set-up).

**Comment by mpadge** [comment]
Travis has just cached on older version. You just need to clear the Travis cache (in settings)

**Comment by edzer** [comment]
Indeed, the cause being a new GDAL version in ubuntugis-unstable ppa needing recompilation of sf.

**Comment by Robinlovelace** [comment]
Many thanks both.

**Comment by Robinlovelace** [comment]
Closing after clearing all caches in Travis in the hope that that fixes it. Will re-open if not!

https://travis-ci.org/ropensci/stplanr
