### ISSUE TITLE
stplanr

### ISSUE THREAD

**Issue by PoorvaITS** [ropensci/stplanr#315]
I tried to generate desire line plot for Bristol_cycle by following the steps from your book, Geo-computation with R and it plotted the map. But when I am trying to use my data by making it read the file in R, I am not able to generate the same for Denmark because the steps which I have followed is generating UK regions only. 

I want to produce a origin-destination desire line map using FromZONEID and ToZONEID of Denmark and can also use latitude-longitude for the same. Can you please suggest the codes and process on how to plot when I have to use a non-UK data and zones.

**Comment by Robinlovelace** [comment]
Hi @PoorvaITS, please can you post some reproducible code that shows what you have done so far? The first stage, as shown in the book you refer to, is to plot the zones and print the origin-destination data: https://geocompr.robinlovelace.net/transport.html#desire-lines

Posting a reproducible example will greatly improve your chances of getting help. For information on how to write a good question with a reproducible example, see here: https://stackoverflow.com/a/5963610/1694378

**Comment by PoorvaITS** [comment]
After installing all the library required, I used coding : 
ride <- read.csv("Ridebooking.csv", header = T, na.strings = "NA")
od_id_order(latitude, longitude)

It is not able to identify the origin and destination zone and hence cannot generate plot.

**Comment by Robinlovelace** [comment]
This is not a reproducible example. However I think I can help. More soon.

**Comment by Robinlovelace** [comment]
Example of a reproducible example:

``` r
x = 1:9
y = x^2

# how do plot the relationship between x and y
plot(x, y)
```

![](https://i.imgur.com/8fEQfOB.png)

<sup>Created on 2019-07-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
Here's code that shows how to do it with just the coordinates in the data, assuming they repeat (may not be most efficient, I think there's need for a function to do this, e.g. called `od_coords2line()`. Thoughts?

**Comment by Robinlovelace** [comment]
Here's the reprex:

``` r
library(stplanr)
#> Registered S3 method overwritten by 'R.oo':
#>   method        from       
#>   throw.default R.methodsS3
    library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
    
    x_coords = 1:5
    
    d = data.frame(
        lon_orig = sample(x_coords, 100, replace = T),
        lat_orig = sample(x_coords, 100, replace = T),
        lon_dest = sample(x_coords, 100, replace = T),
        lat_dest = sample(x_coords, 100, replace = T)
    )
    
    head(d)
#>   lon_orig lat_orig lon_dest lat_dest
#> 1        2        5        5        2
#> 2        2        1        4        3
#> 3        1        2        5        3
#> 4        1        1        1        4
#> 5        1        3        2        1
#> 6        5        3        3        3
    d$orig_id = paste0(d$lon_orig, d$lat_orig)
    d$dest_id = paste0(d$lon_dest, d$lat_dest)
    
    # aggregate to unique od pairs
    d_agg = d %>% 
        group_by(orig_id, dest_id) %>% 
        summarise(n = n())
    
    # create points
    p_orig = d %>% 
        select(lon_orig, lat_orig) %>% 
        group_by(lon_orig, lat_orig) %>% 
        summarise(lon = mean(lon_orig), lat = mean(lat_orig)) %>% 
        sf::st_as_sf(coords = c("lon", "lat"))
    
    plot(p_orig)
```

![](https://i.imgur.com/d3VpCcU.png)

``` r
    p_orig[1] = paste0(p_orig$lon_orig, p_orig$lat_orig)
    
    ?od2line
    l = od2line(flow = d_agg, p_orig)
    plot(l)
```

![](https://i.imgur.com/XBlk48O.png)

<sup>Created on 2019-07-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
To get summaries of other variables at the OD level:

```r
d_agg = d %>% 
  group_by(orig_id, dest_id) %>% 
  summarise(
    n = n()
    # , average_price = mean(price),
    # another_summary = sum_function(...)
    )
```

**Comment by Robinlovelace** [comment]
Hi @PoorvaITS I've modified the function `odcoords2line()` so it can cope with repeated coordinates and counts the number of lines by default. Please try running the following lines of code and let me know how you get on:

```r
# Aim: get od data working
devtools::install_github("ropensci/stplanr", ref = "od_coords2line")
library(stplanr)
library(dplyr)
d_all = readr::read_csv("~/data/Ridebookings.csv")
d = d_all %>% select(from.longitude, from.latitude, to.longitude, to.latitude, everything())
l = od_coords2line(d, crs = 4326)
l
mapview::mapview(l %>% top_n(n = 100, wt = n))
```

I get this:

![image](https://user-images.githubusercontent.com/1825120/60646846-41be7680-9e34-11e9-82ac-b9f06c612fc9.png)

**Comment by PoorvaITS** [comment]
Hello @Robinlovelace, the function odcoords2line() is working and helped me in resolving issue in stplanr. Also, I think desire lines shouldn't be going out of the Denmark, can be some issue with data. But it helped me in generating coordinates (lat, long) to desire lines. 

Many thanks 
Poorva

**Comment by Robinlovelace** [comment]
Great, glad it worked!

**Comment by PoorvaITS** [comment]
Hello @Robinlovelace, I am getting an unexpected error in function od_coords2line. I generated the code and reached to a point where mapview function is not working. Here is the code:

library(tidyverse)
library(base)
library(reprex)
install.packages("stplanr")
library(stplanr)
library(dplyr)
ride_all1 <- read.csv("Pooling.csv",header = T, na.strings = "NA")

df_orig <- ride_all1 %>% select(from.longitude, from.latitude)
summary(df_orig)
df_dest <- ride_all1 %>% select(to.longitude, to.latitude)
summary(df_dest)

ride_all1$origin = paste0(ride_all1$from.longitude, ride_all1$from.latitude)
ride_all1$dest = paste0(ride_all1$to.longitude, ride_all1$to.latitude)


# aggregate to unique od pairs
ride_all1_agg = ride_all1 %>% 
  group_by(origin, dest) %>% 
  summarise(n = n())

# create points
p_orig = ride_all1 %>% 
  select(from.longitude, from.latitude) %>% 
  group_by(from.longitude, from.latitude) %>% 
  summarise(lon = mean(from.longitude), lat = mean(from.latitude)) %>% 
  sf::st_as_sf(coords = c("lon", "lat"))

plot(p_orig)

p_orig[1] = paste0(p_orig$from.longitude, p_orig$from.latitude)
p_orig1 = od2line(flow = ride_all1_agg, p_orig)

plot(p_orig1)


odline = ride_all1 %>% select(from.latitude, from.longitude, to.latitude, to.longitude, everything())
OD <- od_coords2line(odline, crs=4326)
OD
mapview::mapview(OD %>% top_n(n = 100, wt = n))


Also, I tried to create od_matrix from ZoneID but again the function not working.

zoneid <- read.csv("Origindest.csv", header = T, na.strings = "NA")
zone <- zoneid %>% select("FromzoneID", "ToZoneID", everything())
  top_n(n= 90, wt= n)
class(zone)  
zone
zone[1:3]
od_matrix = od_to_odmatrix(zone[1:3])

I would be grateful if you could check the issue.

Thank You

Poorva

**Comment by Robinlovelace** [comment]
Hi @PoorvaITS, can you share the .csv file, or a sample of it, so others can reproduce the issue?

**Comment by PoorvaITS** [comment]
Hey @Robinlovelace, here is the sample file attached:

[Pooling_Sample.xlsx](https://github.com/ropensci/stplanr/files/3529980/Pooling_Sample.xlsx)

**Comment by Robinlovelace** [comment]
``` r
download.file("https://github.com/ropensci/stplanr/files/3529980/Pooling_Sample.xlsx", "Pooling_Sample.xlsx")
d = readxl::read_excel("Pooling_Sample.xlsx")
#> Warning in read_fun(path = enc2native(normalizePath(path)), sheet_i =
#> sheet, : Expecting numeric in L3934 / R3934C12: got 'NA'
d
#> # A tibble: 29,999 x 13
#>     count rideid from.locality from.region from.latitude from.longitude
#>     <dbl>  <dbl> <chr>         <chr>               <dbl>          <dbl>
#>  1 1.41e5 4.01e6 Ã˜lgod        Torvet 8A            55.8           8.62
#>  2 2.60e5 4.19e6 Ã˜lgod        Torvet 14            55.8           8.62
#>  3 9.63e5 5.26e6 Ã˜lgod        Lindbjergv…          55.8           8.65
#>  4 5.07e5 4.57e6 Ã˜lgod        Torvet 8A            55.8           8.62
#>  5 1.03e6 5.34e6 Ã˜lgod        Torvet 8A            55.8           8.62
#>  6 1.76e5 4.06e6 Ã˜lgod        Torvet 8A            55.8           8.62
#>  7 7.53e5 4.96e6 Ã˜lgod        Torvet 8A            55.8           8.62
#>  8 3.23e5 4.28e6 Ã˜lgod        Torvet 8A            55.8           8.62
#>  9 3.23e5 4.28e6 Ã˜lgod        Torvet 8A            55.8           8.62
#> 10 3.23e5 4.28e6 Ã˜lgod        Torvet 8A            55.8           8.62
#> # … with 29,989 more rows, and 7 more variables: to.locality <chr>,
#> #   to.region <chr>, to.latitude <dbl>, to.longitude <dbl>,
#> #   ride.price <dbl>, FromZoneID <dbl>, ToZoneID <chr>

# basic od demo
library(stplanr)
#> Registered S3 method overwritten by 'R.oo':
#>   method        from       
#>   throw.default R.methodsS3
od_lonlat = dplyr::select(d, from.longitude, from.latitude, to.longitude,to.latitude)
l = od_coords2line(od_lonlat)
#> Duplicate OD pairs identified, removing 28231 rows
plot(l)
```

![](https://i.imgur.com/cw2rzm8.png)

``` r

# adding attributes
suppressPackageStartupMessages(library(dplyr))
od_agg = d %>% 
  group_by(from.longitude, from.latitude, to.longitude,to.latitude) %>% 
  summarise(n = n(), price = mean(ride.price))
l2 = od_coords2line(od_agg %>% select(matches("lon|lat")))
desire_lines_agg = sf::st_sf(od_agg, geometry = st_geometry(l2))
#> Error in st_geometry(l2): could not find function "st_geometry"

# plot the result
library(tmap)
tmap_mode("view")
#> tmap mode set to interactive viewing
tm_shape(desire_lines_agg) +
  tm_lines(lwd = "n", col = "price", scale = 9, palette = "-viridis", style = "quantile")
#> Error in as.list.environment(environment()): object 'desire_lines_agg' not found
```

<sup>Created on 2019-09-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
``` r
download.file("https://github.com/ropensci/stplanr/files/3529980/Pooling_Sample.xlsx", "Pooling_Sample.xlsx")
d = readxl::read_excel("Pooling_Sample.xlsx")
#> Warning in read_fun(path = enc2native(normalizePath(path)), sheet_i =
#> sheet, : Expecting numeric in L3934 / R3934C12: got 'NA'
d
#> # A tibble: 29,999 x 13
#>     count rideid from.locality from.region from.latitude from.longitude
#>     <dbl>  <dbl> <chr>         <chr>               <dbl>          <dbl>
#>  1 1.41e5 4.01e6 Ã˜lgod        Torvet 8A            55.8           8.62
#>  2 2.60e5 4.19e6 Ã˜lgod        Torvet 14            55.8           8.62
#>  3 9.63e5 5.26e6 Ã˜lgod        Lindbjergv…          55.8           8.65
#>  4 5.07e5 4.57e6 Ã˜lgod        Torvet 8A            55.8           8.62
#>  5 1.03e6 5.34e6 Ã˜lgod        Torvet 8A            55.8           8.62
#>  6 1.76e5 4.06e6 Ã˜lgod        Torvet 8A            55.8           8.62
#>  7 7.53e5 4.96e6 Ã˜lgod        Torvet 8A            55.8           8.62
#>  8 3.23e5 4.28e6 Ã˜lgod        Torvet 8A            55.8           8.62
#>  9 3.23e5 4.28e6 Ã˜lgod        Torvet 8A            55.8           8.62
#> 10 3.23e5 4.28e6 Ã˜lgod        Torvet 8A            55.8           8.62
#> # … with 29,989 more rows, and 7 more variables: to.locality <chr>,
#> #   to.region <chr>, to.latitude <dbl>, to.longitude <dbl>,
#> #   ride.price <dbl>, FromZoneID <dbl>, ToZoneID <chr>

# basic od demo
library(stplanr)
#> Registered S3 method overwritten by 'R.oo':
#>   method        from       
#>   throw.default R.methodsS3
od_lonlat = dplyr::select(d, from.longitude, from.latitude, to.longitude,to.latitude)
l = od_coords2line(od_lonlat)
#> Duplicate OD pairs identified, removing 28231 rows
plot(l)
```

![](https://i.imgur.com/jjlYyzs.png)

``` r

# adding attributes
suppressPackageStartupMessages(library(dplyr))
od_agg = d %>% 
  group_by(from.longitude, from.latitude, to.longitude,to.latitude) %>% 
  summarise(n = n(), price = mean(ride.price))
l2 = od_coords2line(od_agg %>% select(matches("lon|lat")))
desire_lines_agg = sf::st_sf(od_agg, geometry = sf::st_geometry(l2))

# plot the result
library(tmap)
tmap_mode("view")
#> tmap mode set to interactive viewing
tm_shape(desire_lines_agg) +
  tm_lines(lwd = "n", col = "price", scale = 9, palette = "-viridis", style = "quantile")
#> Linking to GEOS 3.5.1, GDAL 2.1.2, PROJ 4.9.3
#> Legend for line widths not available in view mode.
```

![](https://i.imgur.com/l3CMRvx.png)

<sup>Created on 2019-09-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
Closing for now. Thanks for opening the issue @PoorvaITS and let me know how you got on. Any further feedback on stplanr is welcome.
