### ISSUE TITLE
Question about route_dodgr

### ISSUE THREAD

**Issue by JimShady** [ropensci/stplanr#331]
Hi @Robinlovelace and @mpadge ,

More a question, than an issue. When using `route_dodgr` with coordinates, does the function automatically snap the location to the nearest node on the network before starting the routing? I guess it probably does? I've been going around in circles trying to understand strange routing results, and I think that this must be the reason.

For example ....

```r

centre                 <- c(-0.135076, 51.510115)

# Make a bounding box of 1000 metres

area                    <- st_point(centre) %>%
    st_sfc() %>%
    st_set_crs(4326) %>%
    st_transform(3857) %>%
    st_buffer(1000) %>%
    st_transform(4326) %>%
    st_bbox()

# Download the OSM network for that area

matrix_area             <- matrix(c(area$xmin, area$xmax, area$ymin, area$ymax),2)
colnames(matrix_area)   <- c('X', 'Y')

net                     <- dodgr_streetnet(pts = matrix_area,
                                           expand = 0.1) %>%
                            select(osm_id, highway) %>%
                            mutate(highway = 'pedestrian')

origin <- matrix(c(-0.135076, 51.51011), ncol=2)
dest   <- matrix(c(-0.1382889, 51.5095391), ncol=2)

my_route                <- route_dodgr(from = origin,
                                       to =   dest,
                                       net =  net)

map <- mapview(my_route)
map <- leafem::addFeatures(map, st_point(c(-0.135076, 51.51011)))
leafem::addFeatures(map, st_point(c(-0.1382889, 51.5095391)))
```

![image](https://user-images.githubusercontent.com/2901470/64013832-9ae71580-cb18-11e9-8381-b143d1d9dd29.png)

**Comment by JimShady** [comment]
Although it would be hacky, I wonder if there is a way for me to split all the lines in my network into smaller lines before doing the routing. That would stop this happening I think. Maybe I can use stplanr::line_segment() ? I'll have a go and report back.

**Comment by JimShady** [comment]
Thinking out loud, what the function should probably do is snap to the nearest line, and then to the nearest node of that line. Rather than going straight to the nearest node.

**Comment by mpadge** [comment]
Yeah, you're right that snappping first to line, then to node in line, would be the way to go, but that is waaaay more computationally complicated, and so currently beyond the scope of dodgr, unfortunately.

**Comment by JimShady** [comment]
Fair do, thanks for the clarification.
