### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#334]

**Comment by Robinlovelace** [comment]
![stplanr-logo](https://user-images.githubusercontent.com/1825120/64925905-0c001b80-d7ef-11e9-8f69-85d9a3bd291e.png)

**Comment by mpadge** [comment]
Nice!! I've been meaning to this for a while too. Strong motivation!

**Comment by Robinlovelace** [comment]
![stplanr-logo](https://user-images.githubusercontent.com/1825120/64926325-0eb13f80-d7f4-11e9-9aa1-de92660278fc.png)

**Comment by Robinlovelace** [comment]
![stplanr-logo](https://user-images.githubusercontent.com/1825120/64926377-8e3f0e80-d7f4-11e9-82e8-784b2a0471b6.png)

**Comment by Robinlovelace** [comment]
All thanks to my housemate Pete.

**Comment by Robinlovelace** [comment]
[stplanr-logo.zip](https://github.com/ropensci/stplanr/files/3614199/stplanr-logo.zip)

**Comment by Robinlovelace** [comment]
![stplanr-logo-large](https://user-images.githubusercontent.com/1825120/64927080-fe05c700-d7fd-11e9-834f-4af2ee9e7c5f.png)

**Comment by Robinlovelace** [comment]
[stplanr-logo.zip](https://github.com/ropensci/stplanr/files/3637784/stplanr-logo.zip)


![stplanr-logo-large](https://user-images.githubusercontent.com/1825120/65359536-b794db80-dbf4-11e9-8741-0301001af56f.png)
![stplanr-logo-medium](https://user-images.githubusercontent.com/1825120/65359537-b82d7200-dbf4-11e9-8374-1d57e2da2686.png)
![stplanr-logo](https://user-images.githubusercontent.com/1825120/65359538-b82d7200-dbf4-11e9-8160-96698648e276.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/68866117-d8a51480-06eb-11ea-8a8a-4421d038d5fc.png)
