### ISSUE TITLE
pkdgdown build is failing

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#337]
See https://dev.ropensci.org/blue/organizations/jenkins/stplanr/detail/stplanr/102/pipeline#log-435

Heads-up @jeroen

**Comment by jeroen** [comment]
I upgraded the image to the latest Debian testing + cran packages... maybe think is a real error in the package, not the docs. Let me try to investigate.

**Comment by jeroen** [comment]
There are a few error in the log like this:

```
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
```

Maybe this is related?

**Comment by Robinlovelace** [comment]
>  Maybe this is related?

Could well be an issue with new PROJ versions. 

https://github.com/r-spatial/sf/issues/988

**Comment by Robinlovelace** [comment]
@jeroen can you point me to a Docker image for testing?

**Comment by jeroen** [comment]
The docker image is `ropensci/docs`. 

I think it may be related that debian has upgraded to libproj6.

**Comment by jeroen** [comment]
Maybe there is a caching issue. I'll trash the pkg cache and trigger a build...

**Comment by Robinlovelace** [comment]
Wow a 5+GB container. Also giving it a spin.

**Comment by Robinlovelace** [comment]
Seems to have worked: https://dev.ropensci.org/blue/organizations/jenkins/stplanr/detail/stplanr/111/pipeline

🎉
