### ISSUE TITLE
Use dodgr conditionally

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#346]
> This Suggests: dodgr but does not use it conditionally as required by
§1.1.3.1 of `Writing R Extensions'.  And dodgr has had to be archived.

Based on this https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Suggested-packages I've added this at the beginning of `route_dodgr()`:

https://github.com/ropensci/stplanr/blob/710e7755541a85a85988774f0fbc9876cf650bb8/R/route.R#L98-L100

See https://github.com/ropensci/stplanr/pull/345

Heads-up @mpadge

**Comment by mpadge** [comment]
Yeah, that's what I do for loads of things these days -- the best way to keep direct dependencies down. I've been trying to get `dodgr` back up on CRAN, but it keeps failing when it absolutely should not. Just tried again this morning, so we'll see this time ...

**Comment by mpadge** [comment]
geez, that was a nightmare week, but [`dodgr` is back](https://cran.r-project.org/web/packages/dodgr/index.html). Sorry for the inconvenience!

**Comment by Robinlovelace** [comment]
Great!
