### ISSUE TITLE
line2points and related function with sfc/LINESTRING objects

### ISSUE THREAD

**Issue by agila5** [ropensci/stplanr#361]
While I was experimenting with #358 I faced this error. 

``` r
library(stplanr)
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3

line2points(st_linestring(matrix(c(0, 0, 2, 2), ncol = 2, byrow = TRUE)))
#> Error in UseMethod("line2points"): no applicable method for 'line2points' applied to an object of class "c('XY', 'LINESTRING', 'sfg')"
st_sfc(st_linestring(matrix(c(0, 0, 2, 2), ncol = 2, byrow = TRUE))) %>% 
  line2points()
#> Error in UseMethod("line2points"): no applicable method for 'line2points' applied to an object of class "c('sfc_LINESTRING', 'sfc')"
```

<sup>Created on 2019-11-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The reasons why it's happening are quite clear but I'm not sure what are the best practices. Should I create "ad-hoc" methods for `sfc`/`LINESTRING`? Should I just ignore that and let `line2points `work only on `sf `objects?

**Comment by Robinlovelace** [comment]
I think `line2points()` should work with `sfc` objects also, so I've marked this as a bug.
