### ISSUE TITLE
ITS branding

### ISSUE THREAD

**Issue by mem48** [ropensci/stplanr#363]
@Robinlovelace I had a first go at an ITS hexsticker see https://github.com/ITSLeeds/opentripplanner perhaps a thing to put on all the ITS packages?

**Comment by Robinlovelace** [comment]
Nice. I think that will be ideal for the bottom and perhaps top of the README. But I don't think all ITS packages should have the same hex sticker, how would you tell them apart?! For OTP, I'd recommend a map showing a multi-modal route (e.g. to ITS ; ). This package makes it pretty quick to build them, I could give it a bash if you like? I take your point about linking it to ITS though, [`stplanr` began ](https://cran.r-project.org/src/contrib/Archive/stplanr/)before my time at ITS started but it's definitely linked to the institute. I think at a minimum a link to https://environment.leeds.ac.uk/transport could be added to the readme.

**Comment by mpadge** [comment]
hexSticker has some ... issues ... like, for example, that it's impossible to use a background image - everything is simply overlaid, and the main field is rectangular, not hexagonal (coz it's all ggplot). Just in case that causes you concerns or frustrations, I put together my own code to *properly* fill an entire background, and to do *proper* trimming of the plotting field to an actual hexagon. Code lies in `osmdata` [here](https://github.com/ropensci/osmdata/blob/master/data-raw/hex-script.Rmd) - feel free to pilfer and adapt. (And yes @Robinlovelace, directly inspired by your `stplanr` attempts - thanks!)

**Comment by Robinlovelace** [comment]
Good info @mpadge, should have mentioned that, and the fact that I didn't actually use `hexSticker` but a combination of R, Inkscape and design skills from my housemate Pete!

**Comment by mem48** [comment]
![its_base_hex](https://user-images.githubusercontent.com/15819577/68861557-adb6c280-06e3-11ea-93cc-315360e32cb3.png)
 I had another go, with an opentripplanner unique logo, and the ITS templae we could use on ITS packages. I leave it up to you if you want to put on stplanr.

**Comment by Robinlovelace** [comment]
Nice concept. Note that it would need to be vectorised to work well IMO. See this submission that requires an svg version or at least a high res version of hex logos (that version looks low res): https://docs.google.com/forms/d/e/1FAIpQLSdaLWrD1YWLVMkY7-Lw0YGUqJBpi_n4ZD39BxCIUzq2Kr-v9g/viewform

**Comment by mem48** [comment]
I think that's beyond my image editing skills, but we can try it out on opentripplaner and see how it goes

**Comment by Robinlovelace** [comment]
I'm sure there's a way of adding nice vector graphics + that text into a hex sticker made by the `hexSticker` package or Mark's adaptations of it. Good project for a student maybe?

**Comment by Robinlovelace** [comment]
Currently this is the front page: 

![image](https://user-images.githubusercontent.com/1825120/69235655-cd3d6780-0b89-11ea-9531-b4fec935024c.png)
