### ISSUE TITLE
problem in od2line: !anyNA(x) is not TRUE

### ISSUE THREAD

**Issue by hxd1011** [ropensci/stplanr#371]
Please check following minimal reproducible example: 

We can make sure `x` does not have any nulls.

```
rm(list=ls())
library(sf)
library(stplanr)   
library(spData)

x= world[world$iso_a2 %in% c("AE","US","UK","CN","CA"), c("iso_a2", "geom")]
f = data.frame(rbind(c("UK","US",100),c("AE","UK",200)))
names(f)=c("o","d","cnt")
l = od2line(flow=f,zones=x)
!anyNA(x)

```

**Comment by hxd1011** [comment]
I found the issue: the problem was `x` is not a `sp` but a `sf` adding following two lines will be fine.

`library(sp)`
`x = as(x,'Spatial')`

If possible please change ` !anyNA(x) is not TRUE` error message.

Thanks.

**Comment by Robinlovelace** [comment]
Hi @hxd1011 thanks for reporting the error and the provision of a reproducible example, which I can reproduce below. However, it seems to me the error message *is* clear: the UK is represented by the text string `GB` as shown in the second (fixed) example below.

Are you using the latest version of `stplanr`?
What error message did you get?

``` r
rm(list=ls())
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.2, PROJ 6.2.1
library(stplanr)   
library(spData)

rm(list=ls())
library(sf)
library(stplanr)   
library(spData)

x= world[world$iso_a2 %in% c("AE","US","UK","CN","CA"), c("iso_a2", "geom")]
f = data.frame(rbind(c("UK","US",100),c("AE","UK",200)))
names(f)=c("o","d","cnt")
l = od2line(flow=f,zones=x)
#> Creating centroids representing desire line start and end points.
#> Error: 1 non matching IDs in the origin. ID on row 1 does not match any zone.
#> The first offending id was UK

f$o[1]
#> [1] UK
#> Levels: AE UK
f$o[1] %in% x$iso_a2
#> [1] FALSE


x= world[world$iso_a2 %in% c("AE","US","GB","CN","CA"), c("iso_a2", "geom")]
f = data.frame(rbind(c("GB","US",100),c("AE","GB",200)))
names(f)=c("o","d","cnt")
l = od2line(flow=f,zones=x)
#> Creating centroids representing desire line start and end points.

f$o[1]
#> [1] GB
#> Levels: AE GB
f$o[1] %in% x$iso_a2
#> [1] TRUE
```

<sup>Created on 2019-12-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Note: using the `reprex` package allows you to show the input and output for debugging.

**Comment by hxd1011** [comment]
@Robinlovelace 
Thank you very much for your response. Yes, the problem is the string UK, but not sp or sf. The reason I raised this issue, is that I got confused by the message '!anyNA(x) is not TRUE'. Please see the following picture.

Thanks again for your time and the amazing book and packages.

![image](https://user-images.githubusercontent.com/13385855/70389303-edb55080-19d6-11ea-81a9-11518267f68a.png)

**Comment by Robinlovelace** [comment]
Can you try installing the latest version with:

```
remotes::install_github("ropensci/stplanr")
```
