### ISSUE TITLE
route_graphhopper is out of date

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#389]
I think a package could be the best approach to keep it modular. Improvements on the current function could include:

- [x] use of their updated API
- [x] return of per-segment rather than per-route data
- [x] use of sf

After a bit of searching, I've realised that there's no need to, @crazycapivara has already created a modern interface that returns `sf` objects :tada: Great work!

The only remaining issue from this package's perspective are to:

- [x] Deprecate `route_graphhopper()`
- [ ] Test the use of `route()` with `graphhopper::gh_get_route()` and document as appropriate

**Comment by Robinlovelace** [comment]
Link to the graphopper repo: https://github.com/crazycapivara/graphhopper-r

**Comment by crazycapivara** [comment]
@Robinlovelace Good to know that you want to use the lib. I hope I can publish it soon on cran.

**Comment by crazycapivara** [comment]
crazycapivara/graphhopper-r#8

**Comment by Robinlovelace** [comment]
Great, let me know if you want a hand with that. Looking good to me!

**Comment by Robinlovelace** [comment]
>  Test the use of route() with graphhopper::gh_get_route() and document as appropriate

Still not done but optional extra so closing for now.

**Comment by crazycapivara** [comment]
graphhopper is now on [CRAN](https://cran.r-project.org/web/packages/graphhopper/index.html)
