### ISSUE TITLE
Function to subset route network by igraph group

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#403]
Reproducible example below. It could be useful to split the lines into the component groups:

``` r
u = "https://github.com/ropensci/stplanr/releases/download/0.6.0/r_key_roads_test.Rds"
rnet_disconnected = readRDS(url(u))
sf:::plot.sfc_LINESTRING(rnet_disconnected$geometry)
```

![](https://i.imgur.com/827f761.png)

``` r
touching_list = sf::st_intersects(rnet_disconnected)
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
g = igraph::graph.adjlist(touching_list)
igraph::is_connected(g)
#> [1] FALSE
```

<sup>Created on 2020-05-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
Heads-up @temospena I think I've got it working to solve the problems that we have with such data... What do you think of the below?

``` r
u = "https://github.com/ropensci/stplanr/releases/download/0.6.0/r_key_roads_test.Rds"
rnet_disconnected = readRDS(url(u))
sf:::plot.sfc_LINESTRING(rnet_disconnected$geometry)
```

![](https://i.imgur.com/Na2VYq3.png)

``` r
touching_list = sf::st_intersects(rnet_disconnected)
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
g = igraph::graph.adjlist(touching_list)
igraph::is.directed(g)
#> [1] TRUE
g = igraph::as.undirected(g)
g
#> IGRAPH 1d446e2 U--- 5759 12205 -- 
#> + edges from 1d446e2:
#>  [1]  1-- 1  2-- 2  2-- 3  3-- 3  3-- 4  4-- 4  4-- 5  5-- 5  5-- 6  6-- 6
#> [11]  6-- 7  7-- 7  7-- 8  8-- 8  9-- 9  9--10 10--10 10--11 11--11 11--12
#> [21] 12--12 12--13 13--13 14--14 15--15 16--16 17--17 18--18 19--19 20--20
#> [31] 20--21 21--21 21--22 22--22 22--23 23--23 23--24 24--24 25--25 25--26
#> [41] 26--26 27--27 27--28 28--28 29--29 29--30 30--30 30--31 31--31 31--32
#> [51] 32--32 32--33 33--33 33--34 34--34 34--35 35--35 35--36 36--36 36--37
#> [61] 37--37 37--38 38--38 38--39 39--39 39--40 40--40 40--41 41--41 42--42
#> [71] 42--43 43--43 43--44 44--44 44--45 45--45 45--46 46--46 46--47 47--47
#> [81] 48--48 29--49 48--49 49--49 50--50 50--51 51--51 51--52 52--52 52--53
#> + ... omitted several edges
# wc = igraph::cluster_walktrap(g)
wc = igraph::cluster_louvain(g)
m = igraph::membership(wc)
length(unique(m))
#> [1] 247
summary(m)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>     1.0    63.0   127.0   121.2   166.0   247.0
nrow(rnet_disconnected)
#> [1] 5759
length(m)
#> [1] 5759
rnet_disconnected$membership = m
plot(rnet_disconnected["membership"])
```

![](https://i.imgur.com/nrlsiGm.png)

``` r
# rnet_membership = stplanr::sln_clean_graph()
```

<sup>Created on 2020-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by temospena** [comment]
looks nice.
this example shows that the yellow ones connect to more segments than the blue ones.

but how to assign memberships to a "cluster" with **n** segments, and order them?
for this example, how to assign all segments to a class_membership of connected segments, such as:

- segments in upper left -> 2
- segments in upper right -> 1 (assuming that that "network" has more segments that the other connected ones)
- segments in lower left -> 4
- segments in lower righ -> 3
- all other disconnected segments - > 5,6,7,.....

**Comment by temospena** [comment]
this would be useful to identify disconnected segments of a network, and eventually to assist it's cleaning process.

**Comment by Robinlovelace** [comment]
I think the simpler `igraph::cluster()` function provides the desired result. Didn't know there were so many ways to cluster an `igraph` object! 

``` r
u = "https://github.com/ropensci/stplanr/releases/download/0.6.0/r_key_roads_test.Rds"
rnet_disconnected = readRDS(url(u))
sf:::plot.sfc_LINESTRING(rnet_disconnected$geometry)
```

![](https://i.imgur.com/KBuGcLC.png)

``` r
touching_list = sf::st_intersects(rnet_disconnected)
#> although coordinates are longitude/latitude, st_intersects assumes that they are planar
g = igraph::graph.adjlist(touching_list)
igraph::is.directed(g)
#> [1] TRUE
g = igraph::as.undirected(g)
# g
# wc = igraph::cluster_walktrap(g)
# wc = igraph::cluster_louvain(g)
# wc = igraph::cluster_fast_greedy(g)
wc = igraph::clusters(g)
m = igraph::membership(wc)
length(unique(m))
#> [1] 193
summary(m)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>    1.00   42.00   68.00   68.65   88.00  193.00
nrow(rnet_disconnected)
#> [1] 5759
length(m)
#> [1] 5759
rnet_disconnected$membership = m
rnet_disconnected$membership = as.character(rnet_disconnected$membership)
mapview::mapview(rnet_disconnected["membership"], lwd = 3) 
```

![](https://i.imgur.com/EvaYL1k.png)

<sup>Created on 2020-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
It may seem there are too many clusters, but I think that is just due to the very disjointed nature of the network: 

![image](https://user-images.githubusercontent.com/1825120/98371420-0e958400-2034-11eb-8607-0bb625b00b1c.png)

I think we should add a distance threshold when classifying groups to solve that issue as we did here: https://github.com/cyipt/popupCycleways/blob/master/code/build.R

```r
r_key_buffer = stplanr::geo_buffer(r_key_network_all, dist = 50)
touching_list = st_intersects(r_key_buffer)
g = igraph::graph.adjlist(touching_list)
```

`st_within_distance()` may also work...

**Comment by Robinlovelace** [comment]
Taking a look at this now and trying out functionalising the code:

```r
rnet_group <- function(rnet, distance, cluster_fun = igraph::clusters, char = TRUE) {
  touching_list = sf::st_intersects(rnet)
  g = igraph::graph.adjlist(touching_list)
  # igraph::is.directed(g)
  #> [1] TRUE
  g = igraph::as.undirected(g)
  # g
  # wc = igraph::cluster_walktrap(g)
  # wc = igraph::cluster_louvain(g)
  # wc = igraph::cluster_fast_greedy(g)
  wc = cluster_fun(g)
  m = igraph::membership(wc)
  if(char) m = as.character(m)
  m
}
```

**Comment by Robinlovelace** [comment]
Heads-up @temospena I think this is now fixed thanks to your use case :tada: Please take a look here: https://docs.ropensci.org/stplanr/reference/rnet_group.html

I'm amazed at all the clustering options and honestly not sure of the pros/cons of different ones, but the key functionality of grouping touching (if not connected) graph elements with or without a distance threshold is in there. Interested to see if this works on your route network dataset, glad to have finally had a chance to look at it.

**Comment by temospena** [comment]
Yes, it works great! :+1: 
Very useful to clean up loose segments from an OSM network :)

**Comment by Robinlovelace** [comment]
Write-up: https://twitter.com/robinlovelace/status/1326427943732719616
