### ISSUE TITLE
Bug with viaroute2sldf

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#41]
When testing the example code:

```
exroutes <- viaroute(viapoints=list(data.frame(x=c(-33.5,-33.6,-33.7),y=c(150,150.1,150.2))))
viaroute2sldf(exroutes)
```

I get this error message:

```
Error in data.frame(X1 = c("10", "Sodwalls Station Road", "488", "0",  : 
  arguments imply differing number of rows: 11, 10 
```

Update: this is also sending error messages:

```
exroutes <- viaroute(50, 0, 51, 1)
viaroute2sldf(exroutes)
```

**Comment by richardellison** [comment]
Seems like OSRM running on router.project-osrm.org is returning an extra two variables in each route instruction than is defined in the API. I will put in a fix but will need to look into what the additional two variables mean.

**Comment by richardellison** [comment]
Definition is here: https://github.com/Project-OSRM/osrm-backend/blob/543e77b9befa2798621ec07951891c79d47acb4c/descriptors/json_descriptor.hpp

Additional two variables are pre-turn bearing (string) and pre-turn bearing (numeric).

**Comment by Robinlovelace** [comment]
It seems the two issues were unrelated (should really be a separate bug report).

Still getting a bug with the second:

```
Error: lexical error: inside a string, '\' occurs before a character which it may not.
          bA`EqF~LuY~HyUlJw[~M}X~GeSfQo\zUm^z]_j@zl@cfAlh@ev@fe@qq@fEi
                     (right here) ------^ 
```

Seems like a parsing issue... Any ideas @bdferris?

**Comment by richardellison** [comment]
What are you running to get that error? I tried the example and can't reproduce it.

**Comment by Robinlovelace** [comment]
```
exroutes <- viaroute(50, 0, 51, 1)
viaroute2sldf(exroutes)
```

Updating various packages now to see if that makes a difference.

**Comment by richardellison** [comment]
This seems to be a problem with RCurl not escaping double backslashes with (another) backslash so that when jsonlite::fromJSON parses the string (and strips backslashses) you are still left with a double backslash (to match the original OSRM output). In this case it tries to use \z which is not a valid sequence and so fails. I will try to use gsub to add the extra backslash.

**Comment by richardellison** [comment]
On testing this I realised that that is actually quite a good example of OSRM as it includes a stretch through the Channel Tunnel but still works.

**Comment by Robinlovelace** [comment]
Job done
