### ISSUE TITLE
Add interface to google routing, via mapsapi or googleway

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#410]
Reproducible example below, would be useful to add an example showing this working with `route()`:

``` r

# set key with:
# usethis::edit_r_environ()
key = Sys.getenv("GOOGLE")
remotes::install_github("michaeldorman/mapsapi")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'mapsapi' from a github remote, the SHA1 (5c9fee11) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(mapsapi)

doc = mp_directions(
  origin = "trafalgar square london",
  destination = "hyde park london",
  mode = "transit",
  alternatives = TRUE,
  key = key, 
  quiet = TRUE
)

r = mp_get_routes(doc)
mapview::mapview(r)
```

![](https://i.imgur.com/lL4qkM7.png)

``` r
r$duration_s
#> [1]  804  804  804 1014

# alternative approach ----------------------------------------------------


# library(googleway)
# 
# from = stplanr::geo_code("leeds rail station")
# to = stplanr::geo_code("university of leeds")
# 
# 
# 
# r = google_directions(
#   origin = "trafalgar square london",
#   destination = "hyde park london",
#   mode = "transit",
#   simplify = TRUE,
#   key = key
# )
# 
# class(r)
# str(r)
# names(r)
# 
# summary(r$routes)
# nrow(r$routes[[1]])
# length(r$routes$legs[[1]])
```

<sup>Created on 2020-06-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mpadge** [comment]
Note, however, from [`mapscanner/issues/36`](https://github.com/ropensci/mapscanner/issues/36) that that might be prohibited by google's terms of use. As quoted there from their [terms](https://maps.google.com/help/terms_maps/):

> When using Google Maps/Google Earth, you may not (or allow those acting on your behalf to):
...
d. use Google Maps/Google Earth to create or augment any other mapping-related dataset (including a mapping or navigation dataset, business listings database, mailing list, or telemarketing list) for use in a service that is a substitute for, or a substantially similar service to, Google Maps/Google Earth;

Implementing this idea would involve using google maps in a service in which that could be substituted for other services, so they'd likely have a case against ya.

**Comment by Robinlovelace** [comment]
Good point @mpadge. Based on that assessment we would need to remove this article that used Google data: https://doi.org/10.1016/j.jtrangeo.2017.08.012

I suspect people who work at Google would be happy for such research to go ahead. I think that's fine because academic research doesn't create a service. It would be good to get views from Google employees with knowledge of this and from the authors of the ~500 papers that mention the Google Distance Matrix api: https://scholar.google.com/scholar?q=%22google+distance+matrix%22

**Comment by Robinlovelace** [comment]
Context: I was asked about this for research. Clearly using open source software such as `opentripplanner` and `gtfsrouter` R packages would be preferable but in some places good GTFS data doesn't exist and for large cities it can be time consuming to set-up and validate open source routing.
