### ISSUE TITLE
Document simplify = FALSE setting in overline() with visualisation of output generated by code in the @examples section

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#435]
As outlined in #425. You up for giving a first bash @mem48 ? Can give it a go also. Use case: keeping useful gradient, business and other variables that we have at the segment when creating route network outputs.

**Comment by Robinlovelace** [comment]
This is where I think the example should be documented: 

https://github.com/ropensci/stplanr/blob/2501848c5a003cfe61b55d048f59b805f29bc155/R/overline.R#L174-L181

**Comment by mem48** [comment]
it is documented

#' @param simplify logical, if TRUE group final segments back into lines, default = TRUE

**Comment by Robinlovelace** [comment]
> it is documented

I meant documented in the examples to show users visually how the output differs. The example output will be visible on this help page: https://docs.ropensci.org/stplanr/reference/overline.html#examples

**Comment by Robinlovelace** [comment]
Heads-up @mem48 I've updated the issue title to make it clearer.

**Comment by mem48** [comment]
On a map they would look the same, all that would be different is the number of rows in the results. Perhaps if you gave each line a random colour it would be clear?

**Comment by Robinlovelace** [comment]
> On a map they would look the same, all that would be different is the number of rows in the results. Perhaps if you gave each line a random colour it would be clear?

Good suggestions, was thinking the same.

**Comment by Robinlovelace** [comment]
See #436

**Comment by Robinlovelace** [comment]
Heads-up @mem48 I've merged the PR, closing this issue. Any further ideas welcome. The key for me is to have that result with all the original variables in there - will be useful to keep per segment attributes now provided by the `cyclestreets` package (and presumably `opentripplanner`).
