### ISSUE TITLE
New route_osrm with easy defaults for walking, cycling and driving 

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#449]
To hit URLs like this: https://routing.openstreetmap.de/routed-foot/route/v1/driving/-1.5348243713378906,53.81785699287338;-1.553192138671875,53.80632786808194?overview=false&alternatives=true&steps=true

Just realised that you can get foot/bike/walk routes from the default public server, which is awesome.

Heads-up @rCarto I plan to add a small wrapper around functions in your awesome package, happy to contribute upstream on this also.

**Comment by rCarto** [comment]
Good idea! 
See https://github.com/rCarto/osrm/issues/67

**Comment by Robinlovelace** [comment]
Great, will aim to take a look this eve, will be good to 'kill two birds with one stone' with benefits ppl using osrm directly and through downstream pkgs like stplanr.
