### ISSUE TITLE
CRAN message on internet resources

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#469]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_stplanr.html>.

Please correct before 2021-10-21 to safely retain your package on CRAN.

It seems we need to remind you of the CRAN policy:

'Packages which use Internet resources should fail gracefully with an informative message
if the resource is not available or has changed (and not give a check warning nor error).'

This needs correction whether or not the resource recovers.

The CRAN Team

Aim: test without internet connection.

**Comment by mpadge** [comment]
The [rOpeSci book on "HTTP Testing"](https://books.ropensci.org/http-testing/) has been recently updated, along with lots of the accompanying packages, to help exactly these kinds of issues. It's now much easier than it used to be to use those packages to generate mock HTTP data for tests.
