### ISSUE TITLE
Internal R routing using igraph

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#47]
This should be a fairly simple wrapper around functionality demonstrated here: https://journal.r-project.org/archive/2013-1/eugster-schlesinger.pdf

I've played with it and it definitely works in new contexts: https://github.com/Robinlovelace/Creating-maps-in-R/blob/master/vignettes/osmar-testing.Rmd

**Comment by richardellison** [comment]
Seems useful. I tried a few months ago to use the [shp2igraph](https://cran.r-project.org/web/packages/shp2graph/index.html) to convert from an SP object to an igraph package but couldn't get it to work.

**Comment by Robinlovelace** [comment]
Closing for now. I believe @edzer and @richardellison are implementing this in **[spnetwork](https://github.com/edzer/spnetwork)**. Looking forward to that going live - what are tasks left to do on that btw? Geostat could be a good opportunity to work on it!
