### ISSUE TITLE
Any idea why CRAN released Windows binnary "not available" ?

### ISSUE THREAD

**Issue by rsbivand** [ropensci/stplanr#473]
Now https://cran.r-project.org/package=stplanr says:
Windows binaries: | r-devel: stplanr_0.8.5.zip, r-devel-UCRT: stplanr_0.8.5.zip, r-release: not available, r-oldrel: stplanr_0.8.5.zip
-- | --

Any ideas?

**Comment by Robinlovelace** [comment]
Hi Roger, good question and now I'm not sure... Worth me emailing r-package-devel@r-project.org or CRAN? I hadn't spotted that, thanks for flagging.

**Comment by rsbivand** [comment]
Unsure - I suspect latency after the **igraph** update? **pct** is also not available for Windows release. I'm building a Windows binary for a course participant, should I post it here, (**pct** too)?

**Comment by Robinlovelace** [comment]
Maybe me pushing an incremental release is the quickest way forward... You should be able to get the Windows binary from r-universe.

**Comment by Robinlovelace** [comment]
This may solve the issue in the short term, just tested:

```r
options(repos = c(
  ropensci = 'https://ropensci.r-universe.dev',
  CRAN = 'https://cloud.r-project.org'))
install.packages("stplanr")
```

**Comment by Robinlovelace** [comment]
> I'm building a Windows binary for a course participant, should I post it here, (**pct** too)?

Good plan, important to raise the issue. I've just opened an issue there, thanks for the heads-up.

**Comment by rsbivand** [comment]
[stplanr_0.8.5.zip](https://github.com/ropensci/stplanr/files/7546021/stplanr_0.8.5.zip)
[pct_0.9.3.zip](https://github.com/ropensci/stplanr/files/7546022/pct_0.9.3.zip)

I think latency from the **igraph** update is the reason, pushing both CRAN and packages depending  on **igraph** to wait for current binaries. I don't think the universe is necessarily robust, even though no less robust than my builds Both + CRAN use the same tool train, even generating MD5 keys.

**Comment by Robinlovelace** [comment]
Looks like it is to do with igraph and it looks like the issue remains: https://github.com/igraph/rigraph/issues/489

**Comment by Robinlovelace** [comment]
Plan: try to make `stplanr` Suggest but not Import igraph.

**Comment by Robinlovelace** [comment]
After https://github.com/ropensci/stplanr/pull/475 you now get, for example:

```
> library(stplanr)
> rnet <- rnet_breakup_vertices(stplanr::osm_net_example)
> rnet$group <- rnet_group(rnet)
You must install igraph for this function to work
```

If you don't have igraph.

**Comment by Robinlovelace** [comment]
Update: stplanr no longer Imports `igraph` :tada: planning to submit to CRAN now...

**Comment by Robinlovelace** [comment]
Fixed now by the looks: https://cran.r-project.org/bin/windows/contrib/4.1/stplanr_0.8.5.zip 

I realised that *after* submitting the patched version, will assume the binary will build OK. Closing this for now. Not Importing igraph is a good thing in any case IMO so this issue will lead to good things. Hopefully...
