### ISSUE TITLE
Add terra to remotes?

### ISSUE THREAD

**Issue by maelle** [ropensci/stplanr#480]
:wave: @Robinlovelace!

One of stplanr dependencies has a dependency on terra https://github.com/r-universe/ropensci/runs/5024344041?check_suite_focus=true#step:9:65

```
 namespace 'terra' 1.4-22 is being loaded, but >= 1.5.12 is required
```

However on CRAN 1.5.12 was archived so it's not available from there.

I might have missed discussions about this elsewhere. In the meantime, you might want to add terra to the Remotes field of DESCRIPTION?

**Comment by maelle** [comment]
Wait no I see https://cran.r-project.org/web/packages/terra/index.html

**Comment by maelle** [comment]
Please ignore, it will resolve itself once CRAN has the binary. Sorry about this!

**Comment by Robinlovelace** [comment]
Loving the self fixing bug! See https://github.com/ITSLeeds/TDS/issues/83 for more fallout from this (class of students had to install terra from R Universe).
