### ISSUE TITLE
Breaking change in the new version of osrm

### ISSUE THREAD

**Issue by rCarto** [ropensci/stplanr#488]
Hello @Robinlovelace , 

I'll drop `sp` support in the next version of `osrm`.  One effect of this is I have deprecated the use of `returnclass` arg in all relevant functions (including `osrmRoute()`). Functions will now exclusively return an `sf` object.
This change leads to a few warnings when checking `stplanr` (master and no-sp-2022 branches).

```r
remotes::install_github("riatelab/osrm", ref = "refactor")
```

I could use a message instead of a warning (though it may not be the best practice). What do you think?

**Comment by Robinlovelace** [comment]
Great stuff, I'm also dropping `sp` soon as per #332 and #481. So good timing!
