### ISSUE TITLE
Add additional variables to sldf from gtfs data

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#66]
Taking a look at this now @richardellison using the BART data from SF:

```
download.file("http://transitfeeds.com/p/bart/58/latest/download", "bart.zip")
bart = gtfs2sldf("bart.zip")
```

This extracts 13 variables:

```
names(bart)
 [1] "route_id"         "shape_id"         "route_short_name" "route_long_name"  "route_desc"      
 [6] "route_type"       "route_color"      "route_text_color" "agency_id"        "agency_name"     
[11] "agency_url"       "agency_timezone"  "agency_lang"  
```

Yet there are lots more variables in the various files extracted. Not sure of a good way to add these, particularly as GTFS data is so diverse, but think it worth flagging as an issue!

**Comment by richardellison** [comment]
If the variables are in the routes, trips or agency tables then this should be just a matter of adding another inner_join to join to the data that is already there. For variables in other tables, we would need to decide if we wanted to have a different line associated with each matching row in the table or use a more complex structure of some sort.

**Comment by Robinlovelace** [comment]
Sounds good. The bart.zip feed should provide a good example to prototype some of this.

**Comment by hansthompson** [comment]
I might look into using ropensci/gtfsr to import gtfs data in as it tries to cover all the issues with validation.

**Comment by Robinlovelace** [comment]
Closing as we're not working on this for now. As @hansthompson says https://github.com/ropenscilabs/gtfsr loads and checks GTFS data. We'll need to think about the implications of this work for our gtfs functions. @richardellison I suggest we look for overlaps with gtfs functionality and use theirs if better if/when it gets published on CRAN.
