### ISSUE TITLE
Interesting Tasks on GTFS feeds data

### ISSUE THREAD

**Issue by Emaasit** [ropensci/stplanr#67]
These are some of the questions I would like to ask of the GTFS data. I am preparing functions for these.
1. Calculate a single trip fair: (to calculate the cost of a single trip, that is, boarding a vehicle, traveling for a number of stops, then disembarking)
2. Calculate trips with transfers: To take into account multiple trip segments (that is,one or more transfers)
3. Find trips departing a given stop
4. Find trips arriving at a given stop
5. Find trips between two stops

**Comment by Robinlovelace** [comment]
Sounds good

**Comment by Robinlovelace** [comment]
Closing for now as we're not working on it. Suggest doing this through an interface to [OpenTripPlanner](http://www.opentripplanner.org/). This could either be within a package such as **stplanr** or **gtfsr** (as I suggested [here](https://github.com/ropensci/onboarding/issues/55#issuecomment-237179594)) or, probably the best option, to create a new package, e.g. called **rotp**. Thoughts @richardellison?
