### ISSUE TITLE
Update OSRM functions to support API v5

### ISSUE THREAD

**Issue by richardellison** [ropensci/stplanr#72]
OSRM has recently been updated to use a new API and the demo server will stop supporting v4 at some point in the middle of this year. All OSRM functions need to be updated to support v5. Ideally they should retain compatibility with v4 for people running their own OSRM instances.

**Comment by Robinlovelace** [comment]
Thanks for the heads up - will be good to migrate to the new version as I imagine use of the v4 API will gradually subside.

**Comment by richardellison** [comment]
I think this has been finished for the existing functions with #85. Would be good to add support for the match function at some point though.

**Comment by Robinlovelace** [comment]
Closing for now - can always add the match function as a separate issue. Great work.
