### ISSUE TITLE
put NEWS bits in releases

### ISSUE THREAD

**Issue by sckott** [ropensci/stplanr#80]
hey @Robinlovelace   - We want all rOpenSci pkgs to consistently keep track of changes, following https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news  

* you already keep a `NEWS` file, thanks!
* thanks for git tagging!
* You have used the [releases tab](https://github.com/ropensci/clifro/releases) on this repo to include the associated NEWS items for each tag/version in the past - thanks for that, but can you make sure to always git tag each release, and put the NEWS items in each release in the releases tab? e.g., right now CRAN is at version 0.1.2, while most recent release is at 0.1.1 -  thanks! 😄

**Comment by Robinlovelace** [comment]
Thanks for the reminder - another thing to automate with **devtools** one day perhaps. Think it's done but let me know if there's anything else to fix with it: https://github.com/ropensci/stplanr/releases/tag/0.1.2

**Comment by sckott** [comment]
looks good, thanks

**Comment by sckott** [comment]
@Robinlovelace can you put NEWS bits for latest cran release in release notes again https://github.com/ropensci/stplanr/blob/master/NEWS#L1-L9

**Comment by Robinlovelace** [comment]
Thanks for the nudge @sckott, job done (: https://github.com/ropensci/stplanr/releases/tag/0.1.5

**Comment by sckott** [comment]
thanks
