### ISSUE TITLE
line2route with unroutable lines

### ISSUE THREAD

**Issue by nikolai-b** [ropensci/stplanr#91]
If the the start or end point of the line is far away from the route network (e.g. in a lake) then cyclestreets fails to create a route the line.  I believe this currently fails silently.

I am suggesting an improvement but would like feedback here first:

Make an API call api.cyclestrees.new/route?start=xxx&end=yyy
Listen to response
a) The response is a route - continue as before
b) If response is a straight line (or an error) suggesting that cyclestreets cannot route the line then....
  make 2 calls to graphopper (or another API) to:
  b1) snap xxx to the nearest point in the route network xxx2
  b2) snap yyy to the nearest point in the route network yyy2
  Make another API call api.cyclestrees.new/route?start=xxx2&end=yyy2

**Comment by Robinlovelace** [comment]
This will slow down `line2route`. It already fails well and indicates so in the data. I suggest creating a function that can re-route straight lines generated by `line2route` using a snap to route algorithm. Note that I tested CycleStreets.net's 'snap to route' algorithm and found it is already used internally so instead we should use another one, e.g. Google's or OSRM's, both of which are documented in stplanr I believe.

**Comment by richardellison** [comment]
I would suggest a wrapper script around line2route that runs the process you suggest. You would then get a function that does:

1. Call line2route normally
2. Select a subset of the SpatialLinesDataFrame that contains only the routes that failed in the initial call.
3. Snap each of the coordinates to the nearest point on the route network using another algorithm
4. Run line2route with the subset with updated coordinates
5. Replace the failed routes with the new ones.

**Comment by Robinlovelace** [comment]
Sounds like a good suggestion @richardellison I'm up for giving it a bash. We need it anyway for our work. (Context: @nikolai-b is working on the development of the Propensity to Cycle Tool for which `line2route` was originally written.)

**Comment by nikolai-b** [comment]
First I wanted to check if this has been fixed upstream
Here is a [csv file](https://github.com/ropensci/stplanr/files/403895/snapped.txt) (github wanted me to rename it as a text file...) with the [points that were failing](https://github.com/npct/pct/blob/master/data-sources/failing-points.geojson) and now Cyclestreets seems able to route them.

Looks like it has been fixed upstream!

Ruby code used to check the newer nearest point api:

```ruby
require 'httparty'
require 'rgeo/geo_json'

class CycleStreetNearest
  include HTTParty
  base_uri 'https://api.cyclestreets.net/'
  attr_reader :token, :dir

  def initialize(token = ENV['CYCLESTREET'], dir = 'data-sources')
    @token, @dir = token, dir
  end

  def query
    file = File.read(File.join(dir, "failing-points.geojson"))
    unsnappable = RGeo::GeoJSON.decode(file, json_parser: :json)
    nearestpoints = unsnappable.map do |feature|
      lng = feature.geometry.x
      lat = feature.geometry.y
      [feature.properties['geo_code'], lng, lat] + api_call(lng, lat)
    end
    CSV.open(File.join(dir, "snapped.csv"), "wb") do |csv|
      nearestpoints.each { |point| csv << point }
    end
  end

  private

  def api_call(lng, lat)
    self.class.get('/v2/nearestpoint', query: {
      key: token,
      lonlat: "#{lng},#{lat}"
    })['features'][0]['geometry']['coordinates']
  end
end
```
