### ISSUE TITLE
Add function to split a line into n segments or segments of a given length

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/stplanr#99]
I need this functionality to identify 'parallels' along a train line that have high cycling potential. The full methodology, which constitutes the context of this issue, is as follows: 

"To identify parallels to linear features, a 5 stage methodology was developed. Although this is described below in relation to the Lewes-Uckfield train line, it could be applied to any linear feature of interest:
- Subset cycling desire lines to include only those _whose centrepoint_ pass in close proximity to the train line. This was set as 10 km for this report.
- Break the train line of interest into segments of even distance
- Calculate the angle of the segments of the train line segments and desire lines
- Subset the desire lines again, to include only those that are within a threshold angle (set at 30 degrees) their closes segment
- Aggregate the cycling potential of all parallel lines within the threshold distance of each segment and assign the values to the route segments."

Prototype [code](https://github.com/npct/pct/blob/master/lewes-uckfield.Rmd): 

``` r
pseg = spsample(lewes_uckfield_osgb, n = 5, type = "regular")
plot(pseg)
# try to create 1st line segment
ldf = ggplot2::fortify(lewes_uckfield_osgb)
ldfp = SpatialPointsDataFrame(coords = cbind(ldf$long, ldf$lat), data = ldf)
# find closest point
# install.packages("nabor")
library(nabor)
knn_res = knn(data = coordinates(ldfp), query = coordinates(pseg), k = 1)
sel_nearest = c(knn_res$nn.idx)
points(ldfp[sel_nearest,]) # check they are close by
for(i in 1:(length(sel_nearest) + 1)){
  ids = c(1, sel_nearest, nrow(ldfp))
  if(i == 1){
    l = points_to_line(ldf[ids[i]:ids[(i + 1)],], "long", "lat")
    spChFIDs(l) = i
  } else {
    l_temp = points_to_line(ldf[ids[i]:ids[(i + 1)],], "long", "lat")
    spChFIDs(l_temp) = i
    l = maptools::spRbind(l, l_temp)
  }
}
```

Example of how this will look:
![lewes-uckfield-segments](https://cloud.githubusercontent.com/assets/1825120/18062339/55a606de-6e1e-11e6-9679-3315e2f16a77.png)

**Comment by richardellison** [comment]
There are some functions in the rgeos package that take a fraction and splits a line into segments based on the fraction of the line length. From a quick look I couldn't find if the function that splits the line is exported but it might be worth a look?

**Comment by Robinlovelace** [comment]
Definitely worth a look - can't find anything here though... any idea: http://geos.osgeo.org/doxygen/namespaces.html

**Comment by mdsumner** [comment]
Also trip::interpequal but it's buried deep. trajectories has some thing too. Just fyi, but happy to help if needed

**Comment by Robinlovelace** [comment]
Hi @mdsumner your input will be most appreciated. Starting point: try to reproduce this plot:

![screenshot from 2016-08-31 09-01-10](https://cloud.githubusercontent.com/assets/1825120/18121056/9e40ade4-6f5a-11e6-9ce3-f15efa8509ee.png)

This was created with the following code which I've just put in a pull request. If you could help document, test, break this new `line_segment()` function that would be great, or suggest (perhaps more efficient) alternative implementations, that would be really useful...

```r
#' Find the mid-point of lines
#'
#' This is a wrapper around \code{\link{SpatialLinesMidPoints}} that allows it to find the midpoint
#' of lines that are not projected, which have a lat/long CRS.
#' @inheritParams line2df
#' @export
#' @examples
#' l = routes_fast
line_midpoint = function(l){
  gprojected(l, maptools::SpatialLinesMidPoints)
}

#' Calculate length of lines in geographic CRS
#' @inheritParams line2df
#' @param byid Logical determining whether the length is returned per object (default is true)
#' @export
line_length = function(l, byid = TRUE){
  gprojected(l, rgeos::gLength, byid = byid)
}

#' Divide SpatialLines dataset into regular segments
#' @inheritParams line2df
#' @param n_segments The number of segments to divide the line into
#' @param segment_length The approximate length of segments in the output (overides n_segments if set)
#' @export
#' @examples
#' l = routes_fast[1,]
#' l_seg2 = line_segment(l = l, n_segments = 2)
#' plot(l_seg2, col = l_seg2$group, lwd = 50)
#' l_seg5 = line_segment(l = l, n_segments = 5)
#' plot(l_seg5, col = l_seg5$group, lwd = 30, add = TRUE)
#' l_seg100m = line_segment(l = l, segment_length = 100)
#' plot(l_seg100m, col = l_seg100m$group, lwd = 10, add = TRUE)
#' plot(l, col = "white", add = TRUE)
#' line_segment(l = l, segment_length = 100)
line_segment = function(l, n_segments, segment_length = NA){
  if(!is.na(segment_length)){
    l_length = line_length(l)
    n_segments = round(l_length / segment_length)
  }
  if(n_segments == 2){
    pseg = line_midpoint(l)
  } else {
    pseg = spsample(x = l, n = n_segments - 1, type = "regular")
  }
  l_geom = raster::geom(l)
  l_coords = l_geom[, c("x", "y")]
  knn_res = nabor::knn(data = l_coords, query = coordinates(pseg), k = 1)
  sel_nearest = c(knn_res$nn.idx)
  for(i in 1:(length(sel_nearest) + 1)){
    ids = c(1, sel_nearest, nrow(l))
    if(i == 1){
      l_seg = points2line(l_coords[ids[i]:ids[(i + 1)],])
      spChFIDs(l) = i
    } else if(i == length(sel_nearest) + 1){
      l_temp = points2line(l_coords[ids[i]:nrow(l_coords),])
      spChFIDs(l_temp) = i
      l_seg = maptools::spRbind(l_seg, l_temp)
    } else {
      l_temp = points2line(l_coords[ids[i]:ids[(i + 1)],])
      spChFIDs(l_temp) = i
      l_seg = maptools::spRbind(l_seg, l_temp)
    }
  }
  SpatialLinesDataFrame(l_seg, data.frame(group = 1:i))
}
```

**Comment by mdsumner** [comment]
thank you for this, it's certainly something I want to explore - not sure yet if I can improve on this but I'll let you know how it goes. I *think* it can be a bit simpler by calculating "node" and "measure" space, and then applying approxfun across those to get the start and ends right while maintaining all the input vertices. It's also similar to trip::cut, which really gave me a headache and I'm loathe to revisit, but maybe I could generalize so that distance or time (or other measure) is applied.    

This is already a very interesting solution here btw.

**Comment by Robinlovelace** [comment]
Job done for now I'd say so closing.
